<div style="background-color: #d9edf7; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px;">
    
I - Importation des librairies 

</div>

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

In [2]:
#️⃣ mapper les noms FAO vers ISO3

!pip install pycountry

Requirement already satisfied: pycountry in /opt/anaconda3/lib/python3.13/site-packages (26.2.16)

In [3]:
#️⃣ Conversion noms pays → ISO3
import pycountry

<div style="background-color: #d9edf7; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px;">
    
II - Chargement des fichiers

</div>

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    A – Chargement du fichier: Population  

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [4]:
filepath = 'Population_2000_2018.csv'

# 2. Chargement
pop_df = pd.read_csv(filepath, sep=',', encoding='utf-8', low_memory=False)

# 3. Visualisation professionnelle
print("=" * 50)
print(f"SHAPE     : {pop_df.shape[0]} lignes × {pop_df.shape[1]} colonnes")
print("=" * 50)
print("\nCOLONNES & TYPES :")
print(pop_df.dtypes)
print("\nAPERÇU (5 premières lignes) :")
display(pop_df.head())
print("\nNaN PAR COLONNE :")
print(pop_df.isna().sum())
print(f"\nDOUBLONS : {pop_df.duplicated().sum()}")

==================================================
SHAPE     : 4411 lignes × 15 colonnes
==================================================

COLONNES & TYPES :
Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
Note                       object
dtype: object

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN

NaN PAR COLONNE :
Code Domaine                 0
Domaine                      0
Code zone                    0
Zone                         0
Code Élément                 0
Élément                      0
Code Produit                 0
Produit                      0
Code année                   0
Année                        0
Unité                        0
Valeur                       0
Symbole                      0
Description du Symbole       0
Note                      4153
dtype: int64

DOUBLONS : 0

In [5]:
#️⃣ Analyse exploratoire des données  

print(sorted(pop_df['Année'].unique()))

print(sorted(pop_df['Code Domaine'].unique()))

print(sorted(pop_df['Domaine'].unique()))

print(sorted(pop_df['Code Élément'].unique()))

print(sorted(pop_df['Élément'].unique()))

print(sorted(pop_df['Code Produit'].unique()))

print(sorted(pop_df['Produit'].unique()))

print(sorted(pop_df['Unité'].unique()))

print(sorted(pop_df['Symbole'].unique()))

print(sorted(pop_df['Description du Symbole'].unique()))

[np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018)]
['OA']
['Séries temporelles annuelles']
[np.int64(511)]
['Population totale']
[np.int64(3010)]
['Population-Estimations']
['1000 personnes']
['A', 'X']
['Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées', 'Sources internationales sûres']

In [6]:
#️⃣ Vérifier les pays uniques

print(pop_df['Zone'].nunique())
print(pop_df['Zone'].sort_values().unique())

238
['Afghanistan' 'Afrique du Sud' 'Albanie' 'Algérie' 'Allemagne' 'Andorre'
 'Angola' 'Anguilla' 'Antigua-et-Barbuda' 'Antilles néerlandaises (ex)'
 'Arabie saoudite' 'Argentine' 'Arménie' 'Aruba' 'Australie' 'Autriche'
 'Azerbaïdjan' 'Bahamas' 'Bahreïn' 'Bangladesh' 'Barbade' 'Belgique'
 'Belize' 'Bermudes' 'Bhoutan' 'Bolivie (État plurinational de)'
 'Bonaire, Saint-Eustache et Saba' 'Bosnie-Herzégovine' 'Botswana'
 'Brunéi Darussalam' 'Brésil' 'Bulgarie' 'Burkina Faso' 'Burundi'
 'Bélarus' 'Bénin' 'Cabo Verde' 'Cambodge' 'Cameroun' 'Canada' 'Chili'
 'Chine - RAS de Hong-Kong' 'Chine - RAS de Macao'
 'Chine, Taiwan Province de' 'Chine, continentale' 'Chypre' 'Colombie'
 'Comores' 'Congo' 'Costa Rica' 'Croatie' 'Cuba' 'Curaçao' "Côte d'Ivoire"
 'Danemark' 'Djibouti' 'Dominique' 'El Salvador' 'Espagne' 'Estonie'
 'Eswatini' 'Fidji' 'Finlande' 'France' 'Fédération de Russie' 'Gabon'
 'Gambie' 'Ghana' 'Gibraltar' 'Grenade' 'Groenland' 'Grèce' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guinée' 'Guinée équatoriale' 'Guinée-Bissau' 'Guyana'
 'Guyane française' 'Géorgie' 'Haïti' 'Honduras' 'Hongrie' 'Inde'
 'Indonésie' "Iran (République islamique d')" 'Iraq' 'Irlande' 'Islande'
 'Israël' 'Italie' 'Jamaïque' 'Japon' 'Jordanie' 'Kazakhstan' 'Kenya'
 'Kirghizistan' 'Kiribati' 'Koweït' 'Lesotho' 'Lettonie' 'Liban' 'Libye'
 'Libéria' 'Liechtenstein' 'Lituanie' 'Luxembourg' 'Macédoine du Nord'
 'Madagascar' 'Malaisie' 'Malawi' 'Maldives' 'Mali' 'Malte' 'Maroc'
 'Martinique' 'Maurice' 'Mauritanie' 'Mayotte' 'Mexique'
 'Micronésie (États fédérés de)' 'Monaco' 'Mongolie' 'Montserrat'
 'Monténégro' 'Mozambique' 'Myanmar' 'Namibie' 'Nauru' 'Nicaragua' 'Niger'
 'Nigéria' 'Nioué' 'Norvège' 'Nouvelle-Calédonie' 'Nouvelle-Zélande'
 'Népal' 'Oman' 'Ouganda' 'Ouzbékistan' 'Pakistan' 'Palaos' 'Palestine'
 'Panama' 'Papouasie-Nouvelle-Guinée' 'Paraguay' 'Pays-Bas' 'Philippines'
 'Pologne' 'Polynésie française' 'Porto Rico' 'Portugal' 'Pérou' 'Qatar'
 'Roumanie' "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord" 'Rwanda'
 'République arabe syrienne' 'République centrafricaine'
 'République de Corée' 'République de Moldova' 'République dominicaine'
 'République démocratique du Congo'
 'République démocratique populaire lao'
 'République populaire démocratique de Corée'
 'République-Unie de Tanzanie' 'Réunion' 'Sahara occidental'
 'Saint-Barthélemy' 'Saint-Kitts-et-Nevis' 'Saint-Marin'
 'Saint-Martin (partie française)' 'Saint-Pierre-et-Miquelon'
 'Saint-Siège' 'Saint-Vincent-et-les Grenadines'
 'Sainte-Hélène, Ascension et Tristan da Cunha' 'Sainte-Lucie' 'Samoa'
 'Samoa américaines' 'Sao Tomé-et-Principe' 'Serbie'
 'Serbie-et-Monténégro' 'Seychelles' 'Sierra Leone' 'Singapour'
 'Sint Maarten  (partie néerlandaise)' 'Slovaquie' 'Slovénie' 'Somalie'
 'Soudan' 'Soudan (ex)' 'Soudan du Sud' 'Sri Lanka' 'Suisse' 'Suriname'
 'Suède' 'Sénégal' 'Tadjikistan' 'Tchad' 'Tchéquie' 'Thaïlande'
 'Timor-Leste' 'Togo' 'Tokélaou' 'Tonga' 'Trinité-et-Tobago' 'Tunisie'
 'Turkménistan' 'Turquie' 'Tuvalu' 'Ukraine' 'Uruguay' 'Vanuatu'
 'Venezuela (République bolivarienne du)' 'Viet Nam' 'Yémen' 'Zambie'
 'Zimbabwe' 'Égypte' 'Émirats arabes unis' 'Équateur' 'Érythrée'
 "États-Unis d'Amérique" 'Éthiopie' 'Île de Man' 'Îles Anglo-Normandes'
 'Îles Caïmanes' 'Îles Cook' 'Îles Falkland (Malvinas)' 'Îles Féroé'
 'Îles Mariannes du Nord' 'Îles Marshall' 'Îles Salomon'
 'Îles Turques-et-Caïques' 'Îles Vierges américaines'
 'Îles Vierges britanniques' 'Îles Wallis-et-Futuna']

In [7]:
#️⃣ Conserver uniquement année 2017 

pop_2017_df = pop_df[pop_df['Année'] == 2017].copy()

print("\nAPERÇU (5 premières lignes) :")
display(pop_2017_df.head())

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
17,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,36296.113,X,Sources internationales sûres,NaN
36,OA,Séries temporelles annuelles,202,Afrique du Sud,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,57009.756,X,Sources internationales sûres,NaN
55,OA,Séries temporelles annuelles,3,Albanie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,2884.169,X,Sources internationales sûres,NaN
74,OA,Séries temporelles annuelles,4,Algérie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,41389.189,X,Sources internationales sûres,NaN
93,OA,Séries temporelles annuelles,79,Allemagne,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,82658.409,X,Sources internationales sûres,NaN

In [8]:
#️⃣ Sélection des colonnes pertinentes
pop_2017_df = pop_2017_df[['Zone', 'Année', 'Valeur']].copy()

#️⃣ Renommage clair
pop_2017_df = pop_2017_df.rename(columns={
    'Zone': 'pays',
    'Année': 'annee',
    'Valeur': 'population_milliers'
})

#️⃣ Vérification
print(pop_2017_df.shape)
display(pop_2017_df.head())

(236, 3)

              pays  annee  population_milliers
17     Afghanistan   2017            36296.113
36  Afrique du Sud   2017            57009.756
55         Albanie   2017             2884.169
74         Algérie   2017            41389.189
93       Allemagne   2017            82658.409

In [9]:
#️⃣ Conversion en population réelle
pop_2017_df['population'] = pop_2017_df['population_milliers'] * 1000

#️⃣ Suppression de la colonne intermédiaire
pop_2017_df = pop_2017_df.drop(columns=['population_milliers'])

#️⃣ Vérification
display(pop_2017_df.head())
print(pop_2017_df.describe())

              pays  annee  population
17     Afghanistan   2017  36296113.0
36  Afrique du Sud   2017  57009756.0
55         Albanie   2017   2884169.0
74         Algérie   2017  41389189.0
93       Allemagne   2017  82658409.0

        annee    population
count   236.0  2.360000e+02
mean   2017.0  3.198362e+07
std       0.0  1.318949e+08
min    2017.0  7.930000e+02
25%    2017.0  3.803032e+05
50%    2017.0  5.203510e+06
75%    2017.0  1.930842e+07
max    2017.0  1.421022e+09

In [10]:
#️⃣ Vérification des doublons 

pop_2017_df['pays'].duplicated().sum()

np.int64(0)

In [11]:
#️⃣ Suppression de la colonne 2017 

pop_2017_df = pop_2017_df.drop(columns=['annee'])

display(pop_2017_df.head())

              pays  population
17     Afghanistan  36296113.0
36  Afrique du Sud  57009756.0
55         Albanie   2884169.0
74         Algérie  41389189.0
93       Allemagne  82658409.0

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    B – Chargement du fichier: Disponibilité Alimentaire   

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles
• Variable 2: Taux de dépendance aux importations
• Variable 3: Taille du marché volaille 

</div>

In [12]:
filepath = 'DisponibiliteAlimentaire_2017.csv'


# 2. Chargement
dispo_alimen_2017_df = pd.read_csv(filepath, sep=',', encoding='utf-8', low_memory=False)

# 3. Visualisation professionnelle
print("=" * 50)
print(f"SHAPE     : {dispo_alimen_2017_df.shape[0]} lignes × {dispo_alimen_2017_df.shape[1]} colonnes")
print("=" * 50)
print("\nCOLONNES & TYPES :")
print(dispo_alimen_2017_df.dtypes)
print("\nAPERÇU (5 premières lignes) :")
display(dispo_alimen_2017_df.head())
print("\nNaN PAR COLONNE :")
print(dispo_alimen_2017_df.isna().sum())
print(f"\nDOUBLONS : {dispo_alimen_2017_df.duplicated().sum()}")

==================================================
SHAPE     : 176600 lignes × 14 colonnes
==================================================

COLONNES & TYPES :
Code Domaine               object
Domaine                    object
Code zone                   int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
dtype: object

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4281.0,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2302.0,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.0,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6701.0,S,Données standardisées

NaN PAR COLONNE :
Code Domaine              0
Domaine                   0
Code zone                 0
Zone                      0
Code Élément              0
Élément                   0
Code Produit              0
Produit                   0
Code année                0
Année                     0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

DOUBLONS : 0

In [13]:
#️⃣ Identifier le bon produit: Viande de Volailles

print(sorted(dispo_alimen_2017_df['Produit'].unique()))

['Abats Comestible', 'Agrumes, Autres', 'Alcool, non Comestible', 'Aliments pour enfants', 'Ananas et produits', 'Animaux Aquatiques Autre', 'Arachides Decortiquees', 'Avoine', 'Bananes', 'Bananes plantains', 'Beurre, Ghee', 'Bière', 'Blé et produits', 'Boissons Alcooliques', 'Boissons Fermentés', 'Café et produits', 'Cephalopodes', 'Citrons & Limes et produits', 'Coco (Incl Coprah)', 'Crustacés', 'Crème', 'Céréales, Autres', 'Dattes', 'Edulcorants Autres', 'Feve de Cacao et produits', 'Fruits, Autres', 'Girofles', 'Graines Colza/Moutarde', 'Graines de coton', 'Graines de tournesol', 'Graisses Animales Crue', 'Haricots', 'Huil Plantes Oleif Autr', 'Huile Graines de Coton', "Huile d'Arachide", "Huile d'Olive", 'Huile de Coco', 'Huile de Colza&Moutarde', 'Huile de Germe de Maïs', 'Huile de Palme', 'Huile de Palmistes', 'Huile de Soja', 'Huile de Son de Riz', 'Huile de Sésame', 'Huile de Tournesol', 'Huiles de Foie de Poisso', 'Huiles de Poissons', 'Ignames', 'Lait - Excl Beurre', 'Légumes, Autres', 'Légumineuses Autres et produits', 'Manioc et produits', 'Maïs et produits', 'Miel', 'Millet et produits', 'Miscellanees', 'Mollusques, Autres', 'Noix et produits', 'Oeufs', 'Oignons', 'Olives', 'Oranges, Mandarines', 'Orge et produits', 'Palmistes', 'Pamplemousse et produits', 'Patates douces', 'Perciform', 'Piments', 'Plantes Aquatiques', 'Plantes Oleiferes, Autre', 'Pois', 'Poissons Eau Douce', 'Poissons Marins, Autres', 'Poissons Pelagiques', 'Poivre', 'Pommes de Terre et produits', 'Pommes et produits', 'Racines nda', 'Raisin', 'Riz et produits', 'Seigle et produits', 'Soja', 'Sorgho et produits', 'Sucre Eq Brut', 'Sucre non centrifugé', 'Sucre, betterave', 'Sucre, canne', 'Sésame', 'Thé', 'Tomates et produits', "Viande d'Ovins/Caprins", 'Viande de Anim Aquatiq', 'Viande de Bovins', 'Viande de Suides', 'Viande de Volailles', 'Viande, Autre', 'Vin', 'Épices, Autres']

In [14]:
#️⃣ Conserver le bon produit : Viande de Volailles 

dispo_volaille_df = dispo_alimen_2017_df[
    dispo_alimen_2017_df['Produit'] == 'Viande de Volailles'
].copy()

print("\nAPERÇU (5 premières lignes) :")
display(dispo_volaille_df.head())

print(sorted(dispo_volaille_df['Élément'].unique()))
print(sorted(dispo_volaille_df['Unité'].unique()))

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.0,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.0,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.0,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.0,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.0,S,Données standardisées

['Alimentation pour touristes', 'Aliments pour animaux', 'Autres utilisations (non alimentaire)', 'Disponibilité alimentaire (Kcal/personne/jour)', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité de matière grasse en quantité (g/personne/jour)', 'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 'Résidus', 'Semences', 'Traitement', 'Variation de stock']
['Kcal/personne/jour', 'Milliers de tonnes', 'g/personne/jour', 'kg']

In [15]:
#️⃣ Filtrer le bon produit + les 3 éléments utiles + la bonne unité

dispo_volaille_df = dispo_alimen_2017_df[
    dispo_alimen_2017_df['Produit'] == 'Viande de Volailles'
].copy()

#️⃣ Filtrage des 4 éléments utiles (toutes unités confondues)
elements_utiles = [
    'Disponibilité intérieure',
    'Importations - Quantité',
    'Exportations - Quantité',
    'Disponibilité alimentaire en quantité (kg/personne/an)'
]

dispo_volaille_df = dispo_volaille_df[
    dispo_volaille_df['Élément'].isin(elements_utiles)
].copy()

#️⃣ Vérification
print(dispo_volaille_df.shape)
print(sorted(dispo_volaille_df['Élément'].unique()))
print(sorted(dispo_volaille_df['Unité'].unique()))
display(dispo_volaille_df.head(8))

(647, 14)
['Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité']
['Milliers de tonnes', 'kg']

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
1705,FBS,Nouveaux Bilans Alimentaire,202,Afrique du Sud,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,514.00,S,Données standardisées
1707,FBS,Nouveaux Bilans Alimentaire,202,Afrique du Sud,5911,Exportations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,63.00,S,Données standardisées
1708,FBS,Nouveaux Bilans Alimentaire,202,Afrique du Sud,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2118.00,S,Données standardisées
1713,FBS,Nouveaux Bilans Alimentaire,202,Afrique du Sud,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2017,2017,kg,35.69,Fc,Donnée calculée
2714,FBS,Nouveaux Bilans Alimentaire,3,Albanie,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,38.00,S,Données standardisées

In [16]:
#️⃣ DISPO ALIMENTAIRE — Pivot : 1 ligne = 1 pays

#️⃣ Pivot sur les éléments
dispo_2017_df = dispo_volaille_df.pivot_table(
    index='Zone',
    columns='Élément',
    values='Valeur'
).reset_index()

#️⃣ Supprimer le nom parasite de l'axe columns
dispo_2017_df.columns.name = None

#️⃣ Renommer les colonnes
dispo_2017_df = dispo_2017_df.rename(columns={
    'Zone'                                              : 'pays',
    'Disponibilité intérieure'                          : 'dispo_interieure_kt',
    'Importations - Quantité'                           : 'importations_kt',
    'Exportations - Quantité'                           : 'exportations_kt',
    'Disponibilité alimentaire en quantité (kg/personne/an)' : 'conso_volaille_kg_hab_an'
})

#️⃣ Conversion milliers de tonnes → tonnes pour les 3 premières
for col in ['dispo_interieure_kt', 'importations_kt', 'exportations_kt']:
    dispo_2017_df[col] = dispo_2017_df[col] * 1000

#️⃣ Renommer après conversion
dispo_2017_df = dispo_2017_df.rename(columns={
    'dispo_interieure_kt' : 'dispo_interieure_tonnes',
    'importations_kt'     : 'importations_tonnes',
    'exportations_kt'     : 'exportations_tonnes'
})

#️⃣ Vérification

print(f"SHAPE : {dispo_2017_df.shape[0]} pays × {dispo_2017_df.shape[1]} colonnes")

print(f"\nNaN par colonne :\n{dispo_2017_df.isna().sum()}")
print(f"\nDoublons pays : {dispo_2017_df['pays'].duplicated().sum()}")
display(dispo_2017_df.head())

SHAPE : 172 pays × 5 colonnes

NaN par colonne :
pays                         0
conso_volaille_kg_hab_an     0
dispo_interieure_tonnes      2
exportations_tonnes         37
importations_tonnes          2
dtype: int64

Doublons pays : 0

,pays,conso_volaille_kg_hab_an,dispo_interieure_tonnes,exportations_tonnes,importations_tonnes
0,Afghanistan,1.53,57000.0,NaN,29000.0
1,Afrique du Sud,35.69,2118000.0,63000.0,514000.0
2,Albanie,16.36,47000.0,0.0,38000.0
3,Algérie,6.38,277000.0,0.0,2000.0
4,Allemagne,19.47,1739000.0,646000.0,842000.0

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    C – Chargement du fichier: faostat_Macro_pib_2017

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [17]:
# 🔹 Nouveau fichier
filepath = 'faostat_Macro_pib_2017.csv'

# 2. Chargement
pib_2017_df = pd.read_csv(filepath, sep=',', encoding='utf-8', low_memory=False)

# 3. Visualisation professionnelle
print("=" * 50)
print(f"SHAPE     : {pib_2017_df.shape[0]} lignes × {pib_2017_df.shape[1]} colonnes")
print("=" * 50)

print("\nCOLONNES & TYPES :")
print(pib_2017_df.dtypes)

print("\nAPERÇU (5 premières lignes) :")
display(pib_2017_df.head())

print("\nNaN PAR COLONNE :")
print(pib_2017_df.isna().sum())

print(f"\nDOUBLONS : {pib_2017_df.duplicated().sum()}")

==================================================
SHAPE     : 420 lignes × 15 colonnes
==================================================

COLONNES & TYPES :
Code Domaine               object
Domaine                    object
Code zone (M49)             int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit                int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
Note                      float64
dtype: object

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,MK,Indicateurs macro,4,Afghanistan,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,19034.302820,X,Chiffre de source externe,NaN
1,MK,Indicateurs macro,4,Afghanistan,6119,Valeur US$ par habitant,22008,Produit Intérieur Brut,2017,2017,USD,533.339061,X,Chiffre de source externe,NaN
2,MK,Indicateurs macro,710,Afrique du Sud,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,381136.716379,X,Chiffre de source externe,NaN
3,MK,Indicateurs macro,710,Afrique du Sud,6119,Valeur US$ par habitant,22008,Produit Intérieur Brut,2017,2017,USD,6612.920015,X,Chiffre de source externe,NaN
4,MK,Indicateurs macro,8,Albanie,6110,Valeur US$,22008,Produit Intérieur Brut,2017,2017,Millions d’USD,13019.731318,X,Chiffre de source externe,NaN

NaN PAR COLONNE :
Code Domaine                0
Domaine                     0
Code zone (M49)             0
Zone                        0
Code Élément                0
Élément                     0
Code Produit                0
Produit                     0
Code année                  0
Année                       0
Unité                       0
Valeur                      0
Symbole                     0
Description du Symbole      0
Note                      420
dtype: int64

DOUBLONS : 0

In [18]:
pib_2017_df = pib_2017_df[[
    'Zone',
    'Élément',
    'Valeur'
]].copy()

In [19]:
pib_2017_df = pib_2017_df.pivot_table(
    index='Zone',
    columns='Élément',
    values='Valeur',
    aggfunc='sum'
).reset_index()

In [20]:
pib_2017_df.columns.name = None

In [21]:
pib_2017_df = pib_2017_df.rename(columns={
    'Zone': 'pays',
    'Valeur US$': 'pib_total_millions_usd',
    'Valeur US$ par habitant': 'pib_par_habitant_usd'
})

In [22]:
pib_2017_df['pib_total_millions_usd'] = pib_2017_df['pib_total_millions_usd'].round(2)
pib_2017_df['pib_par_habitant_usd'] = pib_2017_df['pib_par_habitant_usd'].round(0)

In [23]:
pib_2017_df = pib_2017_df[[
    'pays',
    'pib_total_millions_usd',
    'pib_par_habitant_usd'
]]

In [24]:
display(pib_2017_df.head())
print(pib_2017_df.shape)
print(pib_2017_df.columns)
print(pib_2017_df.isna().sum())
print(pib_2017_df['pays'].duplicated().sum())

             pays  pib_total_millions_usd  pib_par_habitant_usd
0     Afghanistan                19034.30                 533.0
1  Afrique du Sud               381136.72                6613.0
2         Albanie                13019.73                4492.0
3         Algérie               170096.99                4080.0
4       Allemagne              3763092.26               45282.0

(210, 3)
Index(['pays', 'pib_total_millions_usd', 'pib_par_habitant_usd'], dtype='object')
pays                      0
pib_total_millions_usd    0
pib_par_habitant_usd      0
dtype: int64
0

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    D – Chargement du fichier: worldbank_stabilite_politique_2017

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [25]:
# SOURCE 3 — Gouvernance World Bank - Correction : skiprows=4 pour sauter les métadonnées World Bank


filepath = 'worldbank_stabilite_politique_2017.csv'


# CORRECTION : skiprows=4 pour ignorer les 4 lignes de métadonnées
gouv_df = pd.read_csv(
    filepath,
    sep=',',
    encoding='utf-8',
    low_memory=False,
    skiprows=4          # ← ligne ajoutée
)

# Visualisation
print("=" * 50)
print(f"SHAPE     : {gouv_df.shape[0]} lignes × {gouv_df.shape[1]} colonnes")
print("=" * 50)
print("\nCOLONNES & TYPES :")
print(gouv_df.dtypes)
print("\nAPERÇU (5 premières lignes) :")
display(gouv_df.head())
print("\nNaN PAR COLONNE :")
print(gouv_df.isna().sum())
print(f"\nDOUBLONS : {gouv_df.duplicated().sum()}")

==================================================
SHAPE     : 266 lignes × 71 colonnes
==================================================

COLONNES & TYPES :
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
                   ...
2022              float64
2023              float64
2024              float64
2025              float64
Unnamed: 70       float64
Length: 71, dtype: object

APERÇU (5 premières lignes) :

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Political Stability and Absence of Violence/Te...,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,...,1.313846,1.337510,1.335807,1.371591,1.431727,1.483080,1.432525,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Political Stability and Absence of Violence/Te...,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Political Stability and Absence of Violence/Te...,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.794976,-2.753441,-2.652540,-2.702721,-2.518676,-2.544956,-2.484081,NaN,NaN,NaN
3,Africa Western and Central,AFW,Political Stability and Absence of Violence/Te...,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Political Stability and Absence of Violence/Te...,PV.EST,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.387895,-0.347209,-0.368412,-0.599918,-0.710481,-0.630109,-0.341505,NaN,NaN,NaN

NaN PAR COLONNE :
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              266
                 ...
2022               61
2023               61
2024              266
2025              266
Unnamed: 70       266
Length: 71, dtype: int64

DOUBLONS : 0

In [26]:
#️⃣ ♦️ Garder uniquement les colonnes utiles

gouv_2017_df = gouv_df[['Country Name', 'Country Code', '2017']].copy()

#️⃣ ♦️  Renommer proprement
gouv_2017_df = gouv_2017_df.rename(columns={
    'Country Name'  : 'pays',
    'Country Code'  : 'iso3',
    '2017'          : 'stabilite_politique'
})

#️⃣ ♦️  Supprimer les lignes sans valeur 2017 (agrégats régionaux surtout)
gouv_2017_df = gouv_2017_df.dropna(subset=['stabilite_politique'])

# 4. Supprimer les agrégats régionaux connus World Bank
agregats_wb = [
    'AFE', 'AFW', 'ARB', 'CEB', 'CSS', 'EAP', 'EAR', 'EAS',
    'ECA', 'ECS', 'EMU', 'EUU', 'FCS', 'HIC', 'HPC', 'IBD',
    'IBT', 'IDA', 'IDB', 'IDX', 'INX', 'LAC', 'LCN', 'LDC',
    'LIC', 'LMC', 'LMY', 'LTE', 'MEA', 'MIC', 'MNA', 'NAC',
    'OED', 'OSS', 'PRE', 'PSS', 'PST', 'SAS', 'SSA', 'SSF',
    'SST', 'TEA', 'TEC', 'TLA', 'TMN', 'TSA', 'TSS', 'UMC',
    'WLD'
]
gouv_2017_df = gouv_2017_df[~gouv_2017_df['iso3'].isin(agregats_wb)]

#️⃣ ♦️  Vérification
print("=" * 50)
print(f"SHAPE     : {gouv_2017_df.shape[0]} pays × {gouv_2017_df.shape[1]} colonnes")
print("=" * 50)
print(f"\nNaN stabilite_politique : {gouv_2017_df['stabilite_politique'].isna().sum()}")
print(f"Doublons iso3           : {gouv_2017_df['iso3'].duplicated().sum()}")
print(f"\nScore min : {gouv_2017_df['stabilite_politique'].min():.3f}")
print(f"Score max : {gouv_2017_df['stabilite_politique'].max():.3f}")
print("\nAPERÇU :")
display(gouv_2017_df.head(10))

==================================================
SHAPE     : 205 pays × 3 colonnes
==================================================

NaN stabilite_politique : 0
Doublons iso3           : 0

Score min : -2.934
Score max : 1.928

APERÇU :

                    pays iso3  stabilite_politique
0                  Aruba  ABW             1.313846
2            Afghanistan  AFG            -2.794976
4                 Angola  AGO            -0.387895
5                Albania  ALB             0.373771
6                Andorra  AND             1.392890
8   United Arab Emirates  ARE             0.601950
9              Argentina  ARG             0.162542
10               Armenia  ARM            -0.626211
11        American Samoa  ASM             1.184324
12   Antigua and Barbuda  ATG             0.732061

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    E – Chargement du fichier: faostat_Import_poulet_2017.csv 

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [27]:
#️⃣ ♦️ SOURCE 5 — Commerce extérieur poulet - faostat_Import_poulet_2017.csv

filepath = 'faostat_Import_poulet_2017.csv'

import_poulet_df = pd.read_csv(filepath, sep=',', encoding='utf-8', low_memory=False)

print("=" * 50)
print(f"SHAPE     : {import_poulet_df.shape[0]} lignes × {import_poulet_df.shape[1]} colonnes")
print("=" * 50)
print("\nCOLONNES & TYPES :")
print(import_poulet_df.dtypes)
print("\nÉLÉMENTS DISPONIBLES :")
print(sorted(import_poulet_df['Élément'].unique()))
print("\nPRODUITS DISPONIBLES :")
print(sorted(import_poulet_df['Produit'].unique()))
print("\nUNITÉS DISPONIBLES :")
print(sorted(import_poulet_df['Unité'].unique()))
print("\nAPERÇU (5 premières lignes) :")
display(import_poulet_df.head())
print("\nNaN PAR COLONNE :")
print(import_poulet_df.isna().sum())
print(f"\nDOUBLONS : {import_poulet_df.duplicated().sum()}")

==================================================
SHAPE     : 388 lignes × 15 colonnes
==================================================

COLONNES & TYPES :
Code Domaine               object
Domaine                    object
Code zone (M49)             int64
Zone                       object
Code Élément                int64
Élément                    object
Code Produit (CPC)          int64
Produit                    object
Code année                  int64
Année                       int64
Unité                      object
Valeur                    float64
Symbole                    object
Description du Symbole     object
Note                       object
dtype: object

ÉLÉMENTS DISPONIBLES :
['Importations - quantité', 'Importations - valeur']

PRODUITS DISPONIBLES :
['Viande, poulet, fraîche ou réfrigérée']

UNITÉS DISPONIBLES :
['1000 USD', 'tonnes']

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,TCL,Cultures et produits animaux,4,Afghanistan,5610,Importations - quantité,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,28937.00,A,Chiffre officiel,NaN
1,TCL,Cultures et produits animaux,4,Afghanistan,5622,Importations - valeur,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,1000 USD,28934.00,A,Chiffre officiel,NaN
2,TCL,Cultures et produits animaux,710,Afrique du Sud,5610,Importations - quantité,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,480345.55,A,Chiffre officiel,NaN
3,TCL,Cultures et produits animaux,710,Afrique du Sud,5622,Importations - valeur,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,1000 USD,410502.00,A,Chiffre officiel,NaN
4,TCL,Cultures et produits animaux,8,Albanie,5610,Importations - quantité,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,17515.47,A,Chiffre officiel,NaN

NaN PAR COLONNE :
Code Domaine                0
Domaine                     0
Code zone (M49)             0
Zone                        0
Code Élément                0
Élément                     0
Code Produit (CPC)          0
Produit                     0
Code année                  0
Année                       0
Unité                       0
Valeur                      0
Symbole                     0
Description du Symbole      0
Note                      310
dtype: int64

DOUBLONS : 0

In [28]:
#️⃣ ♦️ SOURCE 5 — Commerce extérieur poulet — Nettoyage - 1 ligne = 1 pays | import_qty_tonnes | import_value_kusd

#️⃣ ♦️  Pivot : 1 ligne = 1 pays
import_piv = import_poulet_df.pivot_table(
    index='Zone',
    columns='Élément',
    values='Valeur'
).reset_index()

#️⃣ ♦️  Supprimer le nom parasite
import_piv.columns.name = None

#️⃣ ♦️  Renommer
import_poulet_2017_df = import_piv.rename(columns={
    'Zone'                      : 'pays',
    'Importations - quantité'   : 'import_qty_tonnes',
    'Importations - valeur'     : 'import_value_kusd'
})

#️⃣ ♦️  Créer le flag AVANT tout fillna
import_poulet_2017_df['import_declared'] = (
    import_poulet_2017_df['import_qty_tonnes'].notna().astype(int)
)

#️⃣ ♦️  NaN → 0 uniquement APRÈS le flag
import_poulet_2017_df['import_qty_tonnes'] = import_poulet_2017_df['import_qty_tonnes'].fillna(0)
import_poulet_2017_df['import_value_kusd'] = import_poulet_2017_df['import_value_kusd'].fillna(0)

#️⃣ ♦️  Vérification

print(f"SHAPE : {import_poulet_2017_df.shape[0]} pays × {import_poulet_2017_df.shape[1]} colonnes")

print(f"\nNaN par colonne :\n{import_poulet_2017_df.isna().sum()}")
print(f"\nDoublons pays : {import_poulet_2017_df['pays'].duplicated().sum()}")
print(f"\nPays avec import déclaré : {import_poulet_2017_df['import_declared'].sum()}")
print(f"Pays sans import déclaré : {(import_poulet_2017_df['import_declared'] == 0).sum()}")
print("\nAPERÇU :")
display(import_poulet_2017_df.head())

SHAPE : 194 pays × 4 colonnes

NaN par colonne :
pays                 0
import_qty_tonnes    0
import_value_kusd    0
import_declared      0
dtype: int64

Doublons pays : 0

Pays avec import déclaré : 194
Pays sans import déclaré : 0

APERÇU :

             pays  import_qty_tonnes  import_value_kusd  import_declared
0     Afghanistan           28937.00            28934.0                1
1  Afrique du Sud          480345.55           410502.0                1
2         Albanie           17515.47            16481.0                1
3         Algérie               0.40                2.0                1
4       Allemagne          474950.63          1101592.0                1

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    F – faostat_production_poulet_2017.csv 

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [29]:
#️⃣ ♦️ SOURCE 6 — Production locale poulet - Fichier : faostat_production_poulet_2017.csv


filepath = 'faostat_production_poulet_2017.csv'


prod_poulet_df = pd.read_csv(filepath, sep=',', encoding='utf-8', low_memory=False)

print("=" * 50)
print(f"SHAPE     : {prod_poulet_df.shape[0]} lignes × {prod_poulet_df.shape[1]} colonnes")
print("=" * 50)
print("\nÉLÉMENTS DISPONIBLES :")
print(sorted(prod_poulet_df['Élément'].unique()))
print("\nPRODUITS DISPONIBLES :")
print(sorted(prod_poulet_df['Produit'].unique()))
print("\nUNITÉS DISPONIBLES :")
print(sorted(prod_poulet_df['Unité'].unique()))
print("\nAPERÇU (5 premières lignes) :")
display(prod_poulet_df.head())
print("\nNaN PAR COLONNE :")
print(prod_poulet_df.isna().sum())
print(f"\nDOUBLONS : {prod_poulet_df.duplicated().sum()}")

==================================================
SHAPE     : 195 lignes × 15 colonnes
==================================================

ÉLÉMENTS DISPONIBLES :
['Production']

PRODUITS DISPONIBLES :
['Viande, poulet, fraîche ou réfrigérée']

UNITÉS DISPONIBLES :
['tonnes']

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,27637.84,I,Valeur imputée par une agence réceptrice,NaN
1,QCL,Cultures et produits animaux,710,Afrique du Sud,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,1658159.00,A,Chiffre officiel,NaN
2,QCL,Cultures et produits animaux,8,Albanie,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,12912.00,A,Chiffre officiel,NaN
3,QCL,Cultures et produits animaux,12,Algérie,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,364252.17,I,Valeur imputée par une agence réceptrice,NaN
4,QCL,Cultures et produits animaux,276,Allemagne,5510,Production,21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,tonnes,1009565.00,A,Chiffre officiel,NaN

NaN PAR COLONNE :
Code Domaine                0
Domaine                     0
Code zone (M49)             0
Zone                        0
Code Élément                0
Élément                     0
Code Produit (CPC)          0
Produit                     0
Code année                  0
Année                       0
Unité                       0
Valeur                      0
Symbole                     0
Description du Symbole      0
Note                      191
dtype: int64

DOUBLONS : 0

In [30]:
#️⃣ ♦️ SOURCE 6 — Production locale poulet — Nettoyage - Objectif : 1 ligne = 1 pays | production_tonnes

#️⃣ ♦️ Sélection des colonnes utiles
prod_poulet_2017_df = prod_poulet_df[['Zone', 'Valeur']].copy()

#️⃣ ♦️ Renommer
prod_poulet_2017_df = prod_poulet_2017_df.rename(columns={
    'Zone'   : 'pays',
    'Valeur' : 'production_tonnes'
})

#️⃣ ♦️ Vérification valeurs négatives
assert (prod_poulet_2017_df['production_tonnes'].dropna() >= 0).all(), \
    'ERREUR : valeurs négatives détectées'

#️⃣ ♦️ Vérification

print(f"SHAPE : {prod_poulet_2017_df.shape[0]} pays × {prod_poulet_2017_df.shape[1]} colonnes")

print(f"\nNaN production_tonnes : {prod_poulet_2017_df['production_tonnes'].isna().sum()}")
print(f"Doublons pays         : {prod_poulet_2017_df['pays'].duplicated().sum()}")
print(f"\nMin : {prod_poulet_2017_df['production_tonnes'].min()}")
print(f"Max : {prod_poulet_2017_df['production_tonnes'].max()}")
print("\nAPERÇU :")
display(prod_poulet_2017_df.head())

SHAPE : 195 pays × 2 colonnes

NaN production_tonnes : 0
Doublons pays         : 0

Min : 4.03
Max : 19140570.0

APERÇU :

             pays  production_tonnes
0     Afghanistan           27637.84
1  Afrique du Sud         1658159.00
2         Albanie           12912.00
3         Algérie          364252.17
4       Allemagne         1009565.00

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    F – faostat_prix_poulet_2017.csv

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [31]:
#️⃣ ♦️ SOURCE 7 — Prix à la production poulet - Fichier : faostat_prix_poulet_2017.csv


filepath = 'faostat_prix_poulet_2017.csv'


prix_poulet_df = pd.read_csv(filepath, sep=',', encoding='utf-8', low_memory=False)


print(f"SHAPE     : {prix_poulet_df.shape[0]} lignes × {prix_poulet_df.shape[1]} colonnes")

print("\nÉLÉMENTS DISPONIBLES :")
print(sorted(prix_poulet_df['Élément'].unique()))
print("\nPRODUITS DISPONIBLES :")
print(sorted(prix_poulet_df['Produit'].unique()))
print("\nUNITÉS DISPONIBLES :")
print(sorted(prix_poulet_df['Unité'].unique()))
print("\nMOIS DISPONIBLES :")
print(sorted(prix_poulet_df['Mois'].unique()))
print("\nAPERÇU (5 premières lignes) :")
display(prix_poulet_df.head())
print("\nNaN PAR COLONNE :")
print(prix_poulet_df.isna().sum())
print(f"\nDOUBLONS : {prix_poulet_df.duplicated().sum()}")

SHAPE     : 44 lignes × 16 colonnes

ÉLÉMENTS DISPONIBLES :
['Prix à la Production (USD/tonne)']

PRODUITS DISPONIBLES :
['Viande, poulet, fraîche ou réfrigérée']

UNITÉS DISPONIBLES :
['USD']

MOIS DISPONIBLES :
['Valeur annuel']

APERÇU (5 premières lignes) :

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Code Mois,Mois,Unité,Valeur,Symbole,Description du Symbole
0,PP,Prix à la Production,710,Afrique du Sud,5532,Prix à la Production (USD/tonne),21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,7021,Valeur annuel,USD,2015.1,A,Chiffre officiel
1,PP,Prix à la Production,12,Algérie,5532,Prix à la Production (USD/tonne),21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,7021,Valeur annuel,USD,2180.7,A,Chiffre officiel
2,PP,Prix à la Production,276,Allemagne,5532,Prix à la Production (USD/tonne),21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,7021,Valeur annuel,USD,1459.5,A,Chiffre officiel
3,PP,Prix à la Production,32,Argentine,5532,Prix à la Production (USD/tonne),21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,7021,Valeur annuel,USD,1324.1,A,Chiffre officiel
4,PP,Prix à la Production,51,Arménie,5532,Prix à la Production (USD/tonne),21121,"Viande, poulet, fraîche ou réfrigérée",2017,2017,7021,Valeur annuel,USD,3741.2,A,Chiffre officiel

NaN PAR COLONNE :
Code Domaine              0
Domaine                   0
Code zone (M49)           0
Zone                      0
Code Élément              0
Élément                   0
Code Produit (CPC)        0
Produit                   0
Code année                0
Année                     0
Code Mois                 0
Mois                      0
Unité                     0
Valeur                    0
Symbole                   0
Description du Symbole    0
dtype: int64

DOUBLONS : 0

In [32]:
#️⃣ ♦️ SOURCE 7 — Prix à la production poulet — Nettoyage Objectif : 1 ligne = 1 pays | prix_prod_usd_tonne


#️⃣ ♦️ Sélection des colonnes utiles
prix_poulet_2017_df = prix_poulet_df[['Zone', 'Valeur']].copy()

#️⃣ ♦️ Renommer
prix_poulet_2017_df = prix_poulet_2017_df.rename(columns={
    'Zone'   : 'pays',
    'Valeur' : 'prix_prod_usd_tonne'
})

#️⃣ ♦️ Vérification valeurs négatives
assert (prix_poulet_2017_df['prix_prod_usd_tonne'].dropna() >= 0).all(), \
    'ERREUR : valeurs négatives détectées'

#️⃣ ♦️ Vérification

print(f"SHAPE : {prix_poulet_2017_df.shape[0]} pays × {prix_poulet_2017_df.shape[1]} colonnes")

print(f"\nNaN prix_prod_usd_tonne : {prix_poulet_2017_df['prix_prod_usd_tonne'].isna().sum()}")
print(f"Doublons pays           : {prix_poulet_2017_df['pays'].duplicated().sum()}")
print(f"\nMin : {prix_poulet_2017_df['prix_prod_usd_tonne'].min()}")
print(f"Max : {prix_poulet_2017_df['prix_prod_usd_tonne'].max()}")
print("\nAPERÇU :")
display(prix_poulet_2017_df.head(10))

SHAPE : 44 pays × 2 colonnes

NaN prix_prod_usd_tonne : 0
Doublons pays           : 0

Min : 967.5
Max : 6044.0

APERÇU :

                 pays  prix_prod_usd_tonne
0      Afrique du Sud               2015.1
1             Algérie               2180.7
2           Allemagne               1459.5
3           Argentine               1324.1
4             Arménie               3741.2
5            Autriche               2350.9
6         Azerbaïdjan               1783.7
7  Bosnie-Herzégovine                967.5
8   Brunéi Darussalam               3287.7
9          Cabo Verde               4469.3

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    G – cepii_distance_pays.xls

• Import du fichier  
• Vérification du contenu  
• Vérification des données
• Suppresion des colonnes non utiles

</div>

In [33]:
pip install xlrd

Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.13/site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [34]:
#️⃣ ♦️ SOURCE 8 — Distance CEPII - Fichier : cepii_distance_pays.xls
# ⚠️ Format .xls — utiliser engine='xlrd', pas pd.read_csv


dist_df = pd.read_excel(
    'cepii_distance_pays.xls',
    engine='xlrd'
)

print(f"SHAPE     : {dist_df.shape[0]} lignes × {dist_df.shape[1]} colonnes")

print("\nCOLONNES & TYPES :")
print(dist_df.dtypes)
print("\nAPERÇU (5 premières lignes) :")
display(dist_df.head())
print("\nNaN PAR COLONNE :")
print(dist_df.isna().sum())
print(f"\nDOUBLONS : {dist_df.duplicated().sum()}")

SHAPE     : 50176 lignes × 14 colonnes

COLONNES & TYPES :
iso_o             object
iso_d             object
contig             int64
comlang_off        int64
comlang_ethno      int64
colony             int64
comcol             int64
curcol             int64
col45              int64
smctry             int64
dist             float64
distcap          float64
distw             object
distwces          object
dtype: object

APERÇU (5 premières lignes) :

,iso_o,iso_d,contig,comlang_off,comlang_ethno,colony,comcol,curcol,col45,smctry,dist,distcap,distw,distwces
0,ABW,ABW,0,0,0,0,0,0,0,0,5.225315,5.225315,25.09354,23.04723
1,ABW,AFG,0,0,0,0,0,0,0,0,13257.810000,13257.810000,13168.22,13166.37
2,ABW,AGO,0,0,0,0,0,0,0,0,9516.913000,9516.913000,9587.316,9584.193
3,ABW,AIA,0,0,1,0,0,0,0,0,983.268200,983.268200,976.8974,976.8916
4,ABW,ALB,0,0,0,0,0,0,0,0,9091.742000,9091.742000,9091.576,9091.466

NaN PAR COLONNE :
iso_o            0
iso_d            0
contig           0
comlang_off      0
comlang_ethno    0
colony           0
comcol           0
curcol           0
col45            0
smctry           0
dist             0
distcap          0
distw            0
distwces         0
dtype: int64

DOUBLONS : 0

In [35]:
#️⃣ ♦️  SOURCE 8 — Distance CEPII — Nettoyage - Objectif : 1 ligne = 1 pays destination | distance depuis FRA

#️⃣ ♦️ Filtrer : uniquement les lignes où iso_o == 'FRA'et exclure l'auto-distance (FRA → FRA)

dist_2017_df = dist_df[
    (dist_df['iso_o'] == 'FRA') &
    (dist_df['iso_d'] != 'FRA')
].copy()

#️⃣ ♦️ Sélection des colonnes utiles

dist_2017_df = dist_2017_df[[
    'iso_d', 'dist', 'distw', 'contig', 'comlang_off'
]].copy()

#️⃣ ♦️ Convertir distw en numérique (peut contenir des valeurs non numériques → NaN)
dist_2017_df['distw'] = pd.to_numeric(
    dist_2017_df['distw'], errors='coerce'
)

#️⃣ ♦️ Renommer
dist_2017_df = dist_2017_df.rename(columns={
    'iso_d'      : 'iso3',
    'distw'      : 'distance_km',
    'dist'       : 'distance_simple_km'
})

#️⃣ ♦️ Vérification

print(f"SHAPE : {dist_2017_df.shape[0]} pays × {dist_2017_df.shape[1]} colonnes")

print(f"\nNaN par colonne :\n{dist_2017_df.isna().sum()}")
print(f"\nDoublons iso3 : {dist_2017_df['iso3'].duplicated().sum()}")
print(f"\nDistance min : {dist_2017_df['distance_km'].min():.0f} km")
print(f"Distance max : {dist_2017_df['distance_km'].max():.0f} km")
print("\nAPERÇU :")
display(dist_2017_df.head(10))

SHAPE : 223 pays × 5 colonnes

NaN par colonne :
iso3                  0
distance_simple_km    0
distance_km           5
contig                0
comlang_off           0
dtype: int64

Doublons iso3 : 0

Distance min : 474 km
Distance max : 18894 km

APERÇU :

      iso3  distance_simple_km  distance_km  contig  comlang_off
15008  ABW           7685.8840    7716.7520       0            0
15009  AFG           5590.3810    5500.6650       0            0
15010  AGO           6510.3220    6384.8050       0            0
15011  AIA           6710.5700    6743.4270       0            0
15012  ALB           1603.5340    1499.4510       0            0
15013  AND            711.5485     546.5107       1            0
15014  ANT           7638.0260    7541.4990       0            0
15015  ARE           5249.5350    5180.4300       0            0
15016  ARG          11072.2500   10932.3400       0            0
15017  ARM           3434.0710    3402.5700       0            0

<div style="background-color: #fff4e6; padding: 12px; border-left: 5px solid #f97316; border-radius: 6px;">
    
 SIMULATION PÉRIMÈTRE

</div>

In [36]:
#️⃣ ♦️ Combien de pays après toutes jointures - Objectif : vérifier qu'on dépasse 100 pays AVANT de coder


#️⃣ ♦️ Noms des DataFrames et leurs clés
sources = {
    'pop_2017_df'            : 'pays',
    'pib_2017_df'            : 'pays',
    'gouv_2017_df'           : 'iso3',
    'dispo_2017_df'          : 'pays',
    'import_poulet_2017_df'  : 'pays',
    'prod_poulet_2017_df'    : 'pays',
    'prix_poulet_2017_df'    : 'pays',
    'dist_2017_df'           : 'iso3',
}

for nom, cle in sources.items():
    df = eval(nom)
    print(f"{nom:<30} → {df.shape[0]} pays | clé : {cle}")

print("\n")
print("=" * 50)
print("INTERSECTION — pays communs à toutes les sources")
print("(hors prix et distance — sources incomplètes)")
print("=" * 50)

#️⃣ ♦️ Pays communs entre les 5 sources principales (hors prix)
set_pop    = set(pop_2017_df['pays'])
set_pib    = set(pib_2017_df['pays'])
set_dispo  = set(dispo_2017_df['pays'])
set_import = set(import_poulet_2017_df['pays'])
set_prod   = set(prod_poulet_2017_df['pays'])

intersection = set_pop & set_pib & set_dispo & set_import & set_prod
print(f"\nPays communs (pop + pib + dispo + import + prod) : {len(intersection)}")
print("\nPays dans pop mais PAS dans dispo :")
print(sorted(set_pop - set_dispo)[:10], "...")

pop_2017_df                    → 236 pays | clé : pays
pib_2017_df                    → 210 pays | clé : pays
gouv_2017_df                   → 205 pays | clé : iso3
dispo_2017_df                  → 172 pays | clé : pays
import_poulet_2017_df          → 194 pays | clé : pays
prod_poulet_2017_df            → 195 pays | clé : pays
prix_poulet_2017_df            → 44 pays | clé : pays
dist_2017_df                   → 223 pays | clé : iso3


==================================================
INTERSECTION — pays communs à toutes les sources
(hors prix et distance — sources incomplètes)
==================================================

Pays communs (pop + pib + dispo + import + prod) : 162

Pays dans pop mais PAS dans dispo :
['Andorre', 'Anguilla', 'Antilles néerlandaises (ex)', 'Aruba', 'Bahreïn', 'Bermudes', 'Bhoutan', 'Bonaire, Saint-Eustache et Saba', 'Brunéi Darussalam', 'Burundi'] ...

In [37]:
#️⃣ ♦️ SCRIPT 2A — Collecte de tous les noms de pays uniques
# Objectif : construire la liste complète à mapper
# Audit des noms de pays par source - Objectif : lister les noms de pays bruts avant tout mapping
# On regroupe les 6 sources qui utilisent 'pays' comme clé texte
# Les 2 sources ISO3 natif (gouv et dist) sont exclues ici

sources_texte = {
    "pop_2017_df":           pop_2017_df,
    "pib_2017_df":           pib_2017_df,
    "dispo_2017_df":         dispo_2017_df,
    "import_poulet_2017_df": import_poulet_2017_df,
    "prod_poulet_2017_df":   prod_poulet_2017_df,
    "prix_poulet_2017_df":     prix_poulet_2017_df,
}


# Pour chaque source, on extrait les noms de pays uniques
# et on stocke le résultat dans un dictionnaire

audit_pays = {}

for nom_df, df in sources_texte.items():
    pays_uniques = df["pays"].dropna().unique()
    pays_uniques = sorted(pays_uniques)
    audit_pays[nom_df] = set(pays_uniques)
    print(f"\n{'='*50}")
    print(f"Source : {nom_df} — {len(pays_uniques)} pays")
    print(f"{'='*50}")
    for p in pays_uniques:
        print(f"  {p}")

==================================================
Source : pop_2017_df — 236 pays
==================================================
  Afghanistan
  Afrique du Sud
  Albanie
  Algérie
  Allemagne
  Andorre
  Angola
  Anguilla
  Antigua-et-Barbuda
  Antilles néerlandaises (ex)
  Arabie saoudite
  Argentine
  Arménie
  Aruba
  Australie
  Autriche
  Azerbaïdjan
  Bahamas
  Bahreïn
  Bangladesh
  Barbade
  Belgique
  Belize
  Bermudes
  Bhoutan
  Bolivie (État plurinational de)
  Bonaire, Saint-Eustache et Saba
  Bosnie-Herzégovine
  Botswana
  Brunéi Darussalam
  Brésil
  Bulgarie
  Burkina Faso
  Burundi
  Bélarus
  Bénin
  Cabo Verde
  Cambodge
  Cameroun
  Canada
  Chili
  Chine - RAS de Hong-Kong
  Chine - RAS de Macao
  Chine, Taiwan Province de
  Chine, continentale
  Chypre
  Colombie
  Comores
  Congo
  Costa Rica
  Croatie
  Cuba
  Curaçao
  Côte d'Ivoire
  Danemark
  Djibouti
  Dominique
  El Salvador
  Espagne
  Estonie
  Eswatini
  Fidji
  Finlande
  France
  Fédération de Russie
  Gabon
  Gambie
  Ghana
  Gibraltar
  Grenade
  Groenland
  Grèce
  Guadeloupe
  Guam
  Guatemala
  Guinée
  Guinée équatoriale
  Guinée-Bissau
  Guyana
  Guyane française
  Géorgie
  Haïti
  Honduras
  Hongrie
  Inde
  Indonésie
  Iran (République islamique d')
  Iraq
  Irlande
  Islande
  Israël
  Italie
  Jamaïque
  Japon
  Jordanie
  Kazakhstan
  Kenya
  Kirghizistan
  Kiribati
  Koweït
  Lesotho
  Lettonie
  Liban
  Libye
  Libéria
  Liechtenstein
  Lituanie
  Luxembourg
  Macédoine du Nord
  Madagascar
  Malaisie
  Malawi
  Maldives
  Mali
  Malte
  Maroc
  Martinique
  Maurice
  Mauritanie
  Mayotte
  Mexique
  Micronésie (États fédérés de)
  Monaco
  Mongolie
  Montserrat
  Monténégro
  Mozambique
  Myanmar
  Namibie
  Nauru
  Nicaragua
  Niger
  Nigéria
  Nioué
  Norvège
  Nouvelle-Calédonie
  Nouvelle-Zélande
  Népal
  Oman
  Ouganda
  Ouzbékistan
  Pakistan
  Palaos
  Palestine
  Panama
  Papouasie-Nouvelle-Guinée
  Paraguay
  Pays-Bas
  Philippines
  Pologne
  Polynésie française
  Porto Rico
  Portugal
  Pérou
  Qatar
  Roumanie
  Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
  Rwanda
  République arabe syrienne
  République centrafricaine
  République de Corée
  République de Moldova
  République dominicaine
  République démocratique du Congo
  République démocratique populaire lao
  République populaire démocratique de Corée
  République-Unie de Tanzanie
  Réunion
  Sahara occidental
  Saint-Barthélemy
  Saint-Kitts-et-Nevis
  Saint-Marin
  Saint-Martin (partie française)
  Saint-Pierre-et-Miquelon
  Saint-Siège
  Saint-Vincent-et-les Grenadines
  Sainte-Hélène, Ascension et Tristan da Cunha
  Sainte-Lucie
  Samoa
  Samoa américaines
  Sao Tomé-et-Principe
  Serbie
  Seychelles
  Sierra Leone
  Singapour
  Sint Maarten  (partie néerlandaise)
  Slovaquie
  Slovénie
  Somalie
  Soudan
  Soudan du Sud
  Sri Lanka
  Suisse
  Suriname
  Suède
  Sénégal
  Tadjikistan
  Tchad
  Tchéquie
  Thaïlande
  Timor-Leste
  Togo
  Tokélaou
  Tonga
  Trinité-et-Tobago
  Tunisie
  Turkménistan
  Turquie
  Tuvalu
  Ukraine
  Uruguay
  Vanuatu
  Venezuela (République bolivarienne du)
  Viet Nam
  Yémen
  Zambie
  Zimbabwe
  Égypte
  Émirats arabes unis
  Équateur
  Érythrée
  États-Unis d'Amérique
  Éthiopie
  Île de Man
  Îles Anglo-Normandes
  Îles Caïmanes
  Îles Cook
  Îles Falkland (Malvinas)
  Îles Féroé
  Îles Mariannes du Nord
  Îles Marshall
  Îles Salomon
  Îles Turques-et-Caïques
  Îles Vierges américaines
  Îles Vierges britanniques
  Îles Wallis-et-Futuna

==================================================
Source : pib_2017_df — 210 pays
==================================================
  Afghanistan
  Afrique du Sud
  Albanie
  Algérie
  Allemagne
  Andorre
  Angola
  Anguilla
  Antigua-et-Barbuda
  Arabie saoudite
  Argentine
  Arménie
  Aruba
  Australie
  Autriche
  Azerbaïdjan
  Bahamas
  Bahreïn
  Bangladesh
  Barbade
  Belgique
  Belize
  Bermudes
  Bhoutan
  Bolivie (État plurinational de)
  Bosnie-Herzégovine
  Botswana
  Brunéi Darussalam
  Brésil
  Bulgarie
  Burkina Faso
  Burundi
  Bélarus
  Bénin
  Cabo Verde
  Cambodge
  Cameroun
  Canada
  Chili
  Chine - RAS de Hong-Kong
  Chine - RAS de Macao
  Chine, continentale
  Chypre
  Colombie
  Comores
  Congo
  Costa Rica
  Croatie
  Cuba
  Curaçao
  Côte d'Ivoire
  Danemark
  Djibouti
  Dominique
  El Salvador
  Espagne
  Estonie
  Eswatini
  Fidji
  Finlande
  France
  Fédération de Russie
  Gabon
  Gambie
  Ghana
  Grenade
  Groenland
  Grèce
  Guatemala
  Guinée
  Guinée équatoriale
  Guinée-Bissau
  Guyana
  Géorgie
  Haïti
  Honduras
  Hongrie
  Inde
  Indonésie
  Iran (République islamique d')
  Iraq
  Irlande
  Islande
  Israël
  Italie
  Jamaïque
  Japon
  Jordanie
  Kazakhstan
  Kenya
  Kirghizistan
  Kiribati
  Koweït
  Lesotho
  Lettonie
  Liban
  Libye
  Libéria
  Liechtenstein
  Lituanie
  Luxembourg
  Macédoine du Nord
  Madagascar
  Malaisie
  Malawi
  Maldives
  Mali
  Malte
  Maroc
  Maurice
  Mauritanie
  Mexique
  Micronésie (États fédérés de)
  Monaco
  Mongolie
  Montserrat
  Monténégro
  Mozambique
  Myanmar
  Namibie
  Nauru
  Nicaragua
  Niger
  Nigéria
  Norvège
  Nouvelle-Calédonie
  Nouvelle-Zélande
  Népal
  Oman
  Ouganda
  Ouzbékistan
  Pakistan
  Palaos
  Palestine
  Panama
  Papouasie-Nouvelle-Guinée
  Paraguay
  Pays-Bas (Royaume des)
  Philippines
  Pologne
  Polynésie française
  Porto Rico
  Portugal
  Pérou
  Qatar
  Roumanie
  Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
  Rwanda
  République arabe syrienne
  République centrafricaine
  République de Corée
  République de Moldova
  République dominicaine
  République démocratique du Congo
  République démocratique populaire lao
  République populaire démocratique de Corée
  République-Unie de Tanzanie
  Saint-Kitts-et-Nevis
  Saint-Marin
  Saint-Vincent-et-les Grenadines
  Sainte-Lucie
  Samoa
  Sao Tomé-et-Principe
  Serbie
  Seychelles
  Sierra Leone
  Singapour
  Sint Maarten (partie néerlandaise)
  Slovaquie
  Slovénie
  Somalie
  Soudan
  Soudan du Sud
  Sri Lanka
  Suisse
  Suriname
  Suède
  Sénégal
  Tadjikistan
  Tchad
  Tchéquie
  Thaïlande
  Timor-Leste
  Togo
  Tonga
  Trinité-et-Tobago
  Tunisie
  Turkménistan
  Tuvalu
  Türkiye
  Ukraine
  Uruguay
  Vanuatu
  Venezuela (République bolivarienne du)
  Viet Nam
  Yémen
  Zambie
  Zimbabwe
  Égypte
  Émirats arabes unis
  Équateur
  Érythrée
  États-Unis d'Amérique
  Éthiopie
  Îles Caïmanes
  Îles Cook
  Îles Marshall
  Îles Salomon
  Îles Turques-et-Caïques
  Îles Vierges britanniques

==================================================
Source : dispo_2017_df — 172 pays
==================================================
  Afghanistan
  Afrique du Sud
  Albanie
  Algérie
  Allemagne
  Angola
  Antigua-et-Barbuda
  Arabie saoudite
  Argentine
  Arménie
  Australie
  Autriche
  Azerbaïdjan
  Bahamas
  Bangladesh
  Barbade
  Belgique
  Belize
  Bolivie (État plurinational de)
  Bosnie-Herzégovine
  Botswana
  Brésil
  Bulgarie
  Burkina Faso
  Bélarus
  Bénin
  Cabo Verde
  Cambodge
  Cameroun
  Canada
  Chili
  Chine - RAS de Hong-Kong
  Chine - RAS de Macao
  Chine, Taiwan Province de
  Chine, continentale
  Chypre
  Colombie
  Congo
  Costa Rica
  Croatie
  Cuba
  Côte d'Ivoire
  Danemark
  Djibouti
  Dominique
  El Salvador
  Espagne
  Estonie
  Eswatini
  Fidji
  Finlande
  France
  Fédération de Russie
  Gabon
  Gambie
  Ghana
  Grenade
  Grèce
  Guatemala
  Guinée
  Guinée-Bissau
  Guyana
  Géorgie
  Haïti
  Honduras
  Hongrie
  Inde
  Indonésie
  Iran (République islamique d')
  Iraq
  Irlande
  Islande
  Israël
  Italie
  Jamaïque
  Japon
  Jordanie
  Kazakhstan
  Kenya
  Kirghizistan
  Kiribati
  Koweït
  Lesotho
  Lettonie
  Liban
  Libéria
  Lituanie
  Luxembourg
  Macédoine du Nord
  Madagascar
  Malaisie
  Malawi
  Maldives
  Mali
  Malte
  Maroc
  Maurice
  Mauritanie
  Mexique
  Mongolie
  Monténégro
  Mozambique
  Myanmar
  Namibie
  Nicaragua
  Niger
  Nigéria
  Norvège
  Nouvelle-Calédonie
  Nouvelle-Zélande
  Népal
  Oman
  Ouganda
  Ouzbékistan
  Pakistan
  Panama
  Paraguay
  Pays-Bas
  Philippines
  Pologne
  Polynésie française
  Portugal
  Pérou
  Roumanie
  Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
  Rwanda
  République centrafricaine
  République de Corée
  République de Moldova
  République dominicaine
  République démocratique populaire lao
  République populaire démocratique de Corée
  République-Unie de Tanzanie
  Saint-Kitts-et-Nevis
  Saint-Vincent-et-les Grenadines
  Sainte-Lucie
  Samoa
  Sao Tomé-et-Principe
  Serbie
  Sierra Leone
  Slovaquie
  Slovénie
  Soudan
  Sri Lanka
  Suisse
  Suriname
  Suède
  Sénégal
  Tadjikistan
  Tchad
  Tchéquie
  Thaïlande
  Timor-Leste
  Togo
  Trinité-et-Tobago
  Tunisie
  Turkménistan
  Turquie
  Ukraine
  Uruguay
  Vanuatu
  Venezuela (République bolivarienne du)
  Viet Nam
  Yémen
  Zambie
  Zimbabwe
  Égypte
  Émirats arabes unis
  Équateur
  États-Unis d'Amérique
  Éthiopie
  Îles Salomon

==================================================
Source : import_poulet_2017_df — 194 pays
==================================================
  Afghanistan
  Afrique du Sud
  Albanie
  Algérie
  Allemagne
  Angola
  Antigua-et-Barbuda
  Arabie saoudite
  Argentine
  Arménie
  Australie
  Autriche
  Azerbaïdjan
  Bahamas
  Bahreïn
  Bangladesh
  Barbade
  Belgique
  Belize
  Bhoutan
  Bolivie (État plurinational de)
  Bosnie-Herzégovine
  Botswana
  Brunéi Darussalam
  Brésil
  Bulgarie
  Burkina Faso
  Burundi
  Bélarus
  Bénin
  Cabo Verde
  Cambodge
  Cameroun
  Canada
  Chili
  Chine
  Chine - RAS de Hong-Kong
  Chine - RAS de Macao
  Chine, Taiwan Province de
  Chine, continentale
  Chypre
  Colombie
  Comores
  Congo
  Costa Rica
  Croatie
  Cuba
  Côte d'Ivoire
  Danemark
  Djibouti
  Dominique
  El Salvador
  Espagne
  Estonie
  Eswatini
  Fidji
  Finlande
  France
  Fédération de Russie
  Gabon
  Gambie
  Ghana
  Grenade
  Grèce
  Guatemala
  Guinée
  Guinée équatoriale
  Guinée-Bissau
  Guyana
  Géorgie
  Haïti
  Honduras
  Hongrie
  Inde
  Indonésie
  Iran (République islamique d')
  Iraq
  Irlande
  Islande
  Italie
  Jamaïque
  Japon
  Jordanie
  Kazakhstan
  Kenya
  Kirghizistan
  Kiribati
  Koweït
  Lesotho
  Lettonie
  Liban
  Libye
  Libéria
  Lituanie
  Luxembourg
  Macédoine du Nord
  Malaisie
  Malawi
  Maldives
  Mali
  Malte
  Maroc
  Maurice
  Mauritanie
  Mexique
  Micronésie (États fédérés de)
  Mongolie
  Monténégro
  Mozambique
  Myanmar
  Namibie
  Nauru
  Nicaragua
  Niger
  Nigéria
  Nioué
  Norvège
  Nouvelle-Calédonie
  Népal
  Oman
  Ouganda
  Ouzbékistan
  Pakistan
  Palaos
  Palestine
  Panama
  Papouasie-Nouvelle-Guinée
  Pays-Bas (Royaume des)
  Philippines
  Pologne
  Polynésie française
  Portugal
  Pérou
  Qatar
  Roumanie
  Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
  Rwanda
  République arabe syrienne
  République centrafricaine
  République de Corée
  République de Moldova
  République dominicaine
  République démocratique du Congo
  République démocratique populaire lao
  République populaire démocratique de Corée
  République-Unie de Tanzanie
  Saint-Kitts-et-Nevis
  Saint-Vincent-et-les Grenadines
  Sainte-Lucie
  Samoa
  Sao Tomé-et-Principe
  Serbie
  Seychelles
  Sierra Leone
  Singapour
  Slovaquie
  Slovénie
  Somalie
  Soudan
  Soudan du Sud
  Sri Lanka
  Suisse
  Suriname
  Suède
  Sénégal
  Tadjikistan
  Tchad
  Tchéquie
  Thaïlande
  Timor-Leste
  Togo
  Tonga
  Trinité-et-Tobago
  Tunisie
  Turkménistan
  Tuvalu
  Türkiye
  Ukraine
  Uruguay
  Vanuatu
  Venezuela (République bolivarienne du)
  Viet Nam
  Yémen
  Zambie
  Zimbabwe
  Égypte
  Émirats arabes unis
  Érythrée
  États-Unis d'Amérique
  Éthiopie
  Îles Cook
  Îles Féroé
  Îles Marshall
  Îles Salomon

==================================================
Source : prod_poulet_2017_df — 195 pays
==================================================
  Afghanistan
  Afrique du Sud
  Albanie
  Algérie
  Allemagne
  Angola
  Antigua-et-Barbuda
  Arabie saoudite
  Argentine
  Arménie
  Australie
  Autriche
  Azerbaïdjan
  Bahamas
  Bahreïn
  Bangladesh
  Barbade
  Belgique
  Belize
  Bhoutan
  Bolivie (État plurinational de)
  Bosnie-Herzégovine
  Botswana
  Brunéi Darussalam
  Brésil
  Bulgarie
  Burkina Faso
  Burundi
  Bélarus
  Bénin
  Cabo Verde
  Cambodge
  Cameroun
  Canada
  Chili
  Chine
  Chine - RAS de Hong-Kong
  Chine - RAS de Macao
  Chine, Taiwan Province de
  Chine, continentale
  Chypre
  Colombie
  Comores
  Congo
  Costa Rica
  Croatie
  Cuba
  Côte d'Ivoire
  Danemark
  Dominique
  El Salvador
  Espagne
  Estonie
  Eswatini
  Fidji
  Finlande
  France
  Fédération de Russie
  Gabon
  Gambie
  Ghana
  Grenade
  Grèce
  Guatemala
  Guinée
  Guinée équatoriale
  Guinée-Bissau
  Guyana
  Géorgie
  Haïti
  Honduras
  Hongrie
  Inde
  Indonésie
  Iran (République islamique d')
  Iraq
  Irlande
  Islande
  Israël
  Italie
  Jamaïque
  Japon
  Jordanie
  Kazakhstan
  Kenya
  Kirghizistan
  Kiribati
  Koweït
  Lesotho
  Lettonie
  Liban
  Libye
  Libéria
  Lituanie
  Luxembourg
  Macédoine du Nord
  Madagascar
  Malaisie
  Malawi
  Mali
  Malte
  Maroc
  Maurice
  Mauritanie
  Mexique
  Micronésie (États fédérés de)
  Mongolie
  Monténégro
  Mozambique
  Myanmar
  Namibie
  Nauru
  Nicaragua
  Niger
  Nigéria
  Nioué
  Norvège
  Nouvelle-Calédonie
  Nouvelle-Zélande
  Népal
  Oman
  Ouganda
  Ouzbékistan
  Pakistan
  Palestine
  Panama
  Papouasie-Nouvelle-Guinée
  Paraguay
  Pays-Bas (Royaume des)
  Philippines
  Pologne
  Polynésie française
  Porto Rico
  Portugal
  Pérou
  Qatar
  Roumanie
  Royaume-Uni de Grande-Bretagne et d'Irlande du Nord
  Rwanda
  République arabe syrienne
  République centrafricaine
  République de Corée
  République de Moldova
  République dominicaine
  République démocratique du Congo
  République démocratique populaire lao
  République populaire démocratique de Corée
  République-Unie de Tanzanie
  Saint-Kitts-et-Nevis
  Saint-Vincent-et-les Grenadines
  Sainte-Lucie
  Samoa
  Sao Tomé-et-Principe
  Serbie
  Seychelles
  Sierra Leone
  Singapour
  Slovaquie
  Slovénie
  Somalie
  Soudan
  Soudan du Sud
  Sri Lanka
  Suisse
  Suriname
  Suède
  Sénégal
  Tadjikistan
  Tchad
  Tchéquie
  Thaïlande
  Timor-Leste
  Togo
  Tonga
  Trinité-et-Tobago
  Tunisie
  Turkménistan
  Tuvalu
  Türkiye
  Ukraine
  Uruguay
  Vanuatu
  Venezuela (République bolivarienne du)
  Viet Nam
  Yémen
  Zambie
  Zimbabwe
  Égypte
  Émirats arabes unis
  Équateur
  Érythrée
  États-Unis d'Amérique
  Éthiopie
  Îles Cook
  Îles Salomon

==================================================
Source : prix_poulet_2017_df — 44 pays
==================================================
  Afrique du Sud
  Algérie
  Allemagne
  Argentine
  Arménie
  Autriche
  Azerbaïdjan
  Bosnie-Herzégovine
  Brunéi Darussalam
  Cabo Verde
  Chine, continentale
  Chypre
  Danemark
  El Salvador
  Espagne
  Fidji
  Finlande
  France
  Fédération de Russie
  Grenade
  Grèce
  Géorgie
  Islande
  Kazakhstan
  Lettonie
  Liban
  Luxembourg
  Malaisie
  Malte
  Maurice
  Mexique
  Norvège
  Népal
  Palestine
  Qatar
  Roumanie
  Sainte-Lucie
  Sri Lanka
  Suriname
  Togo
  Uruguay
  Viet Nam
  Yémen
  Égypte

In [38]:
#️⃣ ♦️ On rassemble tous les noms de pays de toutes les sources texte en un seul grand ensemble (set = pas de doublons automatiquement)

tous_les_pays = set()

for nom_df, df in sources_texte.items():
    pays_uniques = set(df["pays"].dropna().unique())
    tous_les_pays.update(pays_uniques)   # on ajoute au grand ensemble

# Résultat
print(f"Nombre total de noms de pays uniques à mapper : {len(tous_les_pays)}")

Nombre total de noms de pays uniques à mapper : 240

In [39]:
#️⃣ ♦️ SCRIPT 2B — Mapping automatique pycountry - Objectif : trouver l'ISO3 pour chaque nom de pays

# Dictionnaire de correction manuelle — cas FAO non standards
# Ces noms échouent avec pycountry : on les corrige manuellement

corrections_manuelles = {
    # Noms avec parenthèses FAO
    "Bolivie (État plurinational de)":              "BOL",
    "Iran (République islamique d')":               "IRN",
    "Micronésie (États fédérés de)":               "FSM",
    "Venezuela (République bolivarienne du)":       "VEN",
    "Pays-Bas (Royaume des)":                       "NLD",
    # Noms longs FAO
    "Fédération de Russie":                         "RUS",
    "République démocratique du Congo":             "COD",
    "République populaire démocratique de Corée":   "PRK",
    "République de Corée":                          "KOR",
    "République centrafricaine":                    "CAF",
    "République dominicaine":                       "DOM",
    "République de Moldova":                        "MDA",
    "République arabe syrienne":                    "SYR",
    "République démocratique populaire lao":        "LAO",
    "République-Unie de Tanzanie":                  "TZA",
    # Chines
    "Chine, continentale":                          "CHN",
    "Chine — RAS de Hong-Kong":                     "HKG",
    "Chine — RAS de Macao":                         "MAC",
    "Chine, Taiwan Province de":                    "TWN",
    # Autres cas FAO
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": "GBR",
    "États-Unis d'Amérique":                        "USA",
    "Viet Nam":                                     "VNM",
    "Eswatini":                                     "SWZ",
    "Türkiye":                                      "TUR",
    "Cabo Verde":                                   "CPV",
    "Macédoine du Nord":                            "MKD",
    "Sahara occidental":                            "ESH",
    "Palestine":                                    "PSE",
    "Kosovo":                                       "XKX",
}

# Fonction de recherche ISO3 - Elle essaie pycountry d'abord, puis le dictionnaire manuel

def trouver_iso3(nom_pays):
    # Étape 1 : vérifier le dictionnaire manuel en priorité
    if nom_pays in corrections_manuelles:
        return corrections_manuelles[nom_pays]
    
    # Étape 2 : recherche exacte pycountry
    try:
        pays = pycountry.countries.lookup(nom_pays)
        return pays.alpha_3
    except LookupError:
        pass
    
    # Étape 3 : recherche floue pycountry (fuzzy)
    try:
        resultats = pycountry.countries.search_fuzzy(nom_pays)
        if resultats:
            return resultats[0].alpha_3
    except LookupError:
        pass
    
    # Étape 4 : échec total
    return None

# Application sur tous les noms
mapping_iso3 = {}

for nom in sorted(tous_les_pays):
    iso3 = trouver_iso3(nom)
    mapping_iso3[nom] = iso3

# Résumé
total         = len(mapping_iso3)
trouvés       = sum(1 for v in mapping_iso3.values() if v is not None)
non_trouvés   = sum(1 for v in mapping_iso3.values() if v is None)

print(f"Total        : {total}")
print(f"✅ Mappés    : {trouvés}")
print(f"❌ Échecs    : {non_trouvés}")

# Affichage des échecs uniquement
print("\n=== Noms sans ISO3 trouvé ===\n")
for nom, iso3 in sorted(mapping_iso3.items()):
    if iso3 is None:
        print(f"  ❌ {nom}")

Total        : 240
✅ Mappés    : 115
❌ Échecs    : 125

=== Noms sans ISO3 trouvé ===

  ❌ Afrique du Sud
  ❌ Albanie
  ❌ Algérie
  ❌ Allemagne
  ❌ Andorre
  ❌ Antigua-et-Barbuda
  ❌ Antilles néerlandaises (ex)
  ❌ Arabie saoudite
  ❌ Arménie
  ❌ Australie
  ❌ Autriche
  ❌ Azerbaïdjan
  ❌ Bahreïn
  ❌ Barbade
  ❌ Belgique
  ❌ Bermudes
  ❌ Bhoutan
  ❌ Bonaire, Saint-Eustache et Saba
  ❌ Bosnie-Herzégovine
  ❌ Brésil
  ❌ Bulgarie
  ❌ Cambodge
  ❌ Cameroun
  ❌ Chili
  ❌ Chine
  ❌ Chine - RAS de Hong-Kong
  ❌ Chine - RAS de Macao
  ❌ Chypre
  ❌ Colombie
  ❌ Comores
  ❌ Croatie
  ❌ Danemark
  ❌ Dominique
  ❌ Espagne
  ❌ Estonie
  ❌ Fidji
  ❌ Finlande
  ❌ Gambie
  ❌ Grenade
  ❌ Groenland
  ❌ Grèce
  ❌ Guinée
  ❌ Guinée équatoriale
  ❌ Guinée-Bissau
  ❌ Guyane française
  ❌ Géorgie
  ❌ Hongrie
  ❌ Indonésie
  ❌ Irlande
  ❌ Islande
  ❌ Italie
  ❌ Jamaïque
  ❌ Japon
  ❌ Jordanie
  ❌ Kirghizistan
  ❌ Koweït
  ❌ Lettonie
  ❌ Liban
  ❌ Libye
  ❌ Lituanie
  ❌ Malaisie
  ❌ Maroc
  ❌ Maurice
  ❌ Mauritanie
  ❌ Mexique
  ❌ Mongolie
  ❌ Namibie
  ❌ Nioué
  ❌ Norvège
  ❌ Nouvelle-Zélande
  ❌ Ouganda
  ❌ Ouzbékistan
  ❌ Palaos
  ❌ Papouasie-Nouvelle-Guinée
  ❌ Pays-Bas
  ❌ Pologne
  ❌ Porto Rico
  ❌ Pérou
  ❌ Roumanie
  ❌ Saint-Kitts-et-Nevis
  ❌ Saint-Marin
  ❌ Saint-Martin (partie française)
  ❌ Saint-Siège
  ❌ Saint-Vincent-et-les Grenadines
  ❌ Sainte-Hélène, Ascension et Tristan da Cunha
  ❌ Sainte-Lucie
  ❌ Samoa américaines
  ❌ Sao Tomé-et-Principe
  ❌ Serbie
  ❌ Singapour
  ❌ Sint Maarten  (partie néerlandaise)
  ❌ Sint Maarten (partie néerlandaise)
  ❌ Slovaquie
  ❌ Slovénie
  ❌ Somalie
  ❌ Soudan
  ❌ Soudan du Sud
  ❌ Suisse
  ❌ Suède
  ❌ Tadjikistan
  ❌ Tchad
  ❌ Tchéquie
  ❌ Thaïlande
  ❌ Tokélaou
  ❌ Trinité-et-Tobago
  ❌ Tunisie
  ❌ Turquie
  ❌ Zambie
  ❌ Égypte
  ❌ Émirats arabes unis
  ❌ Érythrée
  ❌ Éthiopie
  ❌ Île de Man
  ❌ Îles Anglo-Normandes
  ❌ Îles Caïmanes
  ❌ Îles Cook
  ❌ Îles Falkland (Malvinas)
  ❌ Îles Féroé
  ❌ Îles Mariannes du Nord
  ❌ Îles Marshall
  ❌ Îles Salomon
  ❌ Îles Turques-et-Caïques
  ❌ Îles Vierges américaines
  ❌ Îles Vierges britanniques
  ❌ Îles Wallis-et-Futuna

In [40]:
#️⃣ ♦️ SCRIPT 2C — Test country_converter

# Installation
import subprocess
subprocess.run(["pip", "install", "country_converter", "--quiet"])

import country_converter as coco

#️⃣ ♦️ Test rapide sur les cas problématiques identifiés
cas_test = [
    "Afrique du Sud",
    "Allemagne", 
    "Brésil",
    "Fédération de Russie",
    "Iran (République islamique d')",
    "Bolivie (État plurinational de)",
    "Chine, continentale",
    "Chine — RAS de Hong-Kong",
    "États-Unis d'Amérique",
    "Viet Nam",
    "République démocratique du Congo",
    "Côte d'Ivoire",
]

print("=== Test country_converter ===\n")
for nom in cas_test:
    iso3 = coco.convert(names=nom, to="ISO3", not_found=None)
    statut = "✅" if iso3 else "❌"
    print(f"  {statut} {nom} → {iso3}")

Afrique du Sud not found in regex
Allemagne not found in regex
Brésil not found in regex
Fédération de Russie not found in regex
Bolivie (État plurinational de) not found in regex
Chine, continentale not found in regex
États-Unis d'Amérique not found in regex
République démocratique du Congo not found in regex

=== Test country_converter ===

  ✅ Afrique du Sud → Afrique du Sud
  ✅ Allemagne → Allemagne
  ✅ Brésil → Brésil
  ✅ Fédération de Russie → Fédération de Russie
  ✅ Iran (République islamique d') → IRN
  ✅ Bolivie (État plurinational de) → Bolivie (État plurinational de)
  ✅ Chine, continentale → Chine, continentale
  ✅ Chine — RAS de Hong-Kong → HKG
  ✅ États-Unis d'Amérique → États-Unis d'Amérique
  ✅ Viet Nam → VNM
  ✅ République démocratique du Congo → République démocratique du Congo
  ✅ Côte d'Ivoire → CIV

In [41]:
#️⃣ ♦️ SCRIPT 2D — Test country_converter corrigé - On filtre les retours qui ne sont pas des vrais codes ISO3

import country_converter as coco
import re

def est_iso3_valide(code):
    # Un vrai code ISO3 = exactement 3 lettres majuscules
    if code is None:
        return False
    return bool(re.match(r'^[A-Z]{3}$', str(code)))

cas_test = [
    "Afrique du Sud",
    "Allemagne",
    "Brésil",
    "Fédération de Russie",
    "Iran (République islamique d')",
    "Bolivie (État plurinational de)",
    "Chine, continentale",
    "Chine — RAS de Hong-Kong",
    "États-Unis d'Amérique",
    "Viet Nam",
    "République démocratique du Congo",
    "Côte d'Ivoire",
    "Allemagne",
    "Japon",
    "Singapour",
    "Turquie",
]

print("=== Test country_converter corrigé ===\n")
for nom in cas_test:
    iso3 = coco.convert(names=nom, to="ISO3", not_found=None)
    if not est_iso3_valide(iso3):
        iso3 = None
    statut = "✅" if iso3 else "❌"
    print(f"  {statut} {nom} → {iso3}")

Afrique du Sud not found in regex

=== Test country_converter corrigé ===

  ❌ Afrique du Sud → None

Allemagne not found in regex
Brésil not found in regex
Fédération de Russie not found in regex
Bolivie (État plurinational de) not found in regex
Chine, continentale not found in regex
États-Unis d'Amérique not found in regex
République démocratique du Congo not found in regex
Allemagne not found in regex
Japon not found in regex

  ❌ Allemagne → None
  ❌ Brésil → None
  ❌ Fédération de Russie → None
  ✅ Iran (République islamique d') → IRN
  ❌ Bolivie (État plurinational de) → None
  ❌ Chine, continentale → None
  ✅ Chine — RAS de Hong-Kong → HKG
  ❌ États-Unis d'Amérique → None
  ✅ Viet Nam → VNM
  ❌ République démocratique du Congo → None
  ✅ Côte d'Ivoire → CIV
  ❌ Allemagne → None
  ❌ Japon → None

Singapour not found in regex
Turquie not found in regex

  ❌ Singapour → None
  ❌ Turquie → None

In [42]:
#️⃣ ♦️ SCRIPT 2E — Mapping via noms français natifs pycountry

import pycountry

# pycountry contient les noms officiels en français
# via la locale 'fra' — on va construire un dictionnaire
# nom_français → ISO3 depuis la base pycountry elle-même

mapping_fr = {}

for pays in pycountry.countries:
    # Nom officiel en anglais → ISO3 (toujours disponible)
    mapping_fr[pays.name] = pays.alpha_3
    
    # Nom commun en anglais si disponible (ex: "Iran" vs "Iran, Islamic Republic of")
    if hasattr(pays, 'common_name'):
        mapping_fr[pays.common_name] = pays.alpha_3

# Affichage de contrôle : est-ce que les noms français y sont ?
tests = ["Allemagne", "Japon", "Brésil", "Afrique du Sud", "Singapour"]
print("=== Test noms français dans pycountry ===\n")
for t in tests:
    print(f"  {t} → {mapping_fr.get(t, 'ABSENT')}")

print(f"\nTaille du dictionnaire pycountry : {len(mapping_fr)} entrées")

=== Test noms français dans pycountry ===

  Allemagne → ABSENT
  Japon → ABSENT
  Brésil → ABSENT
  Afrique du Sud → ABSENT
  Singapour → ABSENT

Taille du dictionnaire pycountry : 260 entrées

In [43]:
#️⃣ ♦️ SCRIPT 2F — Dictionnaire complet FAO français → ISO3 - Source : audit manuel des 240 noms identifiés

mapping_fao_iso3 = {
    "Afghanistan": "AFG", "Afrique du Sud": "ZAF", "Albanie": "ALB",
    "Algérie": "DZA", "Allemagne": "DEU", "Andorre": "AND",
    "Angola": "AGO", "Anguilla": "AIA", "Antigua-et-Barbuda": "ATG",
    "Antilles néerlandaises (ex)": "ANT", "Arabie saoudite": "SAU",
    "Argentine": "ARG", "Arménie": "ARM", "Aruba": "ABW",
    "Australie": "AUS", "Autriche": "AUT", "Azerbaïdjan": "AZE",
    "Bahamas": "BHS", "Bahreïn": "BHR", "Bangladesh": "BGD",
    "Barbade": "BRB", "Belgique": "BEL", "Belize": "BLZ",
    "Bermudes": "BMU", "Bhoutan": "BTN",
    "Bolivie (État plurinational de)": "BOL",
    "Bonaire, Saint-Eustache et Saba": "BES",
    "Bosnie-Herzégovine": "BIH", "Botswana": "BWA",
    "Brunéi Darussalam": "BRN", "Brésil": "BRA",
    "Bulgarie": "BGR", "Burkina Faso": "BFA", "Burundi": "BDI",
    "Bélarus": "BLR", "Bénin": "BEN", "Cabo Verde": "CPV",
    "Cambodge": "KHM", "Cameroun": "CMR", "Canada": "CAN",
    "Chili": "CHL", "Chine": "CHN", "Chine, continentale": "CHN",
    "Chine — RAS de Hong-Kong": "HKG", "Chine — RAS de Macao": "MAC",
    "Chine, Taiwan Province de": "TWN", "Chypre": "CYP",
    "Colombie": "COL", "Comores": "COM", "Congo": "COG",
    "Costa Rica": "CRI", "Croatie": "HRV", "Cuba": "CUB",
    "Curaçao": "CUW", "Côte d'Ivoire": "CIV", "Danemark": "DNK",
    "Djibouti": "DJI", "Dominique": "DMA", "El Salvador": "SLV",
    "Espagne": "ESP", "Estonie": "EST", "Eswatini": "SWZ",
    "Fidji": "FJI", "Finlande": "FIN", "France": "FRA",
    "Fédération de Russie": "RUS", "Gabon": "GAB", "Gambie": "GMB",
    "Ghana": "GHA", "Gibraltar": "GIB", "Grenade": "GRD",
    "Groenland": "GRL", "Grèce": "GRC", "Guadeloupe": "GLP",
    "Guam": "GUM", "Guatemala": "GTM", "Guinée": "GIN",
    "Guinée équatoriale": "GNQ", "Guinée-Bissau": "GNB",
    "Guyana": "GUY", "Guyane française": "GUF", "Géorgie": "GEO",
    "Haïti": "HTI", "Honduras": "HND", "Hongrie": "HUN",
    "Inde": "IND", "Indonésie": "IDN",
    "Iran (République islamique d')": "IRN",
    "Iraq": "IRQ", "Irlande": "IRL", "Islande": "ISL",
    "Israël": "ISR", "Italie": "ITA", "Jamaïque": "JAM",
    "Japon": "JPN", "Jordanie": "JOR", "Kazakhstan": "KAZ",
    "Kenya": "KEN", "Kirghizistan": "KGZ", "Kiribati": "KIR",
    "Koweït": "KWT", "Lesotho": "LSO", "Lettonie": "LVA",
    "Liban": "LBN", "Libye": "LBY", "Libéria": "LBR",
    "Liechtenstein": "LIE", "Lituanie": "LTU", "Luxembourg": "LUX",
    "Macédoine du Nord": "MKD", "Madagascar": "MDG",
    "Malaisie": "MYS", "Malawi": "MWI", "Maldives": "MDV",
    "Mali": "MLI", "Malte": "MLT", "Maroc": "MAR",
    "Martinique": "MTQ", "Maurice": "MUS", "Mauritanie": "MRT",
    "Mayotte": "MYT", "Mexique": "MEX",
    "Micronésie (États fédérés de)": "FSM",
    "Monaco": "MCO", "Mongolie": "MNG", "Montserrat": "MSR",
    "Monténégro": "MNE", "Mozambique": "MOZ", "Myanmar": "MMR",
    "Namibie": "NAM", "Nauru": "NRU", "Nicaragua": "NIC",
    "Niger": "NER", "Nigéria": "NGA", "Nioué": "NIU",
    "Norvège": "NOR", "Nouvelle-Calédonie": "NCL",
    "Nouvelle-Zélande": "NZL", "Népal": "NPL", "Oman": "OMN",
    "Ouganda": "UGA", "Ouzbékistan": "UZB", "Pakistan": "PAK",
    "Palaos": "PLW", "Palestine": "PSE", "Panama": "PAN",
    "Papouasie-Nouvelle-Guinée": "PNG", "Paraguay": "PRY",
    "Pays-Bas": "NLD", "Pays-Bas (Royaume des)": "NLD",
    "Philippines": "PHL", "Pologne": "POL",
    "Polynésie française": "PYF", "Porto Rico": "PRI",
    "Portugal": "PRT", "Pérou": "PER", "Qatar": "QAT",
    "Roumanie": "ROU",
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": "GBR",
    "Rwanda": "RWA", "République arabe syrienne": "SYR",
    "République centrafricaine": "CAF", "République de Corée": "KOR",
    "République de Moldova": "MDA",
    "République dominicaine": "DOM",
    "République démocratique du Congo": "COD",
    "République démocratique populaire lao": "LAO",
    "République populaire démocratique de Corée": "PRK",
    "République-Unie de Tanzanie": "TZA", "Réunion": "REU",
    "Sahara occidental": "ESH",
    "Saint-Barthélemy": "BLM",
    "Saint-Kitts-et-Nevis": "KNA", "Saint-Marin": "SMR",
    "Saint-Martin (partie française)": "MAF",
    "Saint-Pierre-et-Miquelon": "SPM", "Saint-Siège": "VAT",
    "Saint-Vincent-et-les Grenadines": "VCT",
    "Sainte-Hélène, Ascension et Tristan da Cunha": "SHN",
    "Sainte-Lucie": "LCA", "Samoa": "WSM",
    "Samoa américaines": "ASM", "Sao Tomé-et-Principe": "STP",
    "Serbie": "SRB", "Seychelles": "SYC", "Sierra Leone": "SLE",
    "Singapour": "SGP", "Sint Maarten (partie néerlandaise)": "SXM",
    "Sint Maarten  (partie néerlandaise)": "SXM",
    "Slovaquie": "SVK", "Slovénie": "SVN", "Somalie": "SOM",
    "Soudan": "SDN", "Soudan du Sud": "SSD", "Sri Lanka": "LKA",
    "Suisse": "CHE", "Suriname": "SUR", "Suède": "SWE",
    "Sénégal": "SEN", "Tadjikistan": "TJK", "Tchad": "TCD",
    "Tchéquie": "CZE", "Thaïlande": "THA", "Timor-Leste": "TLS",
    "Togo": "TGO", "Tokélaou": "TKL", "Tonga": "TON",
    "Trinité-et-Tobago": "TTO", "Tunisie": "TUN",
    "Turkménistan": "TKM", "Turquie": "TUR", "Türkiye": "TUR",
    "Tuvalu": "TUV", "Ukraine": "UKR", "Uruguay": "URY",
    "Vanuatu": "VUT",
    "Venezuela (République bolivarienne du)": "VEN",
    "Viet Nam": "VNM", "Yémen": "YEM", "Zambie": "ZMB",
    "Zimbabwe": "ZWE", "Égypte": "EGY", "Émirats arabes unis": "ARE",
    "Équateur": "ECU", "Érythrée": "ERI",
    "États-Unis d'Amérique": "USA", "Éthiopie": "ETH",
    "Île de Man": "IMN", "Îles Anglo-Normandes": "JEY",
    "Îles Caïmanes": "CYM", "Îles Cook": "COK",
    "Îles Falkland (Malvinas)": "FLK", "Îles Féroé": "FRO",
    "Îles Mariannes du Nord": "MNP", "Îles Marshall": "MHL",
    "Îles Salomon": "SLB", "Îles Turques-et-Caïques": "TCA",
    "Îles Vierges américaines": "VIR",
    "Îles Vierges britanniques": "VGB",
    "Îles Wallis-et-Futuna": "WLF",
    # Cas PIB spécifiques
    "Nouvelle-Zélande": "NZL",
}

print(f"Dictionnaire construit : {len(mapping_fao_iso3)} entrées")

# Vérification sur les cas problématiques identifiés
tests = [
    "Allemagne", "Japon", "Brésil", "Afrique du Sud",
    "Fédération de Russie", "Iran (République islamique d')",
    "Chine, continentale", "États-Unis d'Amérique",
    "République démocratique du Congo",
]
print("\n=== Vérification cas critiques ===\n")
for t in tests:
    iso3 = mapping_fao_iso3.get(t, "❌ ABSENT")
    print(f"  {t} → {iso3}")

Dictionnaire construit : 240 entrées

=== Vérification cas critiques ===

  Allemagne → DEU
  Japon → JPN
  Brésil → BRA
  Afrique du Sud → ZAF
  Fédération de Russie → RUS
  Iran (République islamique d') → IRN
  Chine, continentale → CHN
  États-Unis d'Amérique → USA
  République démocratique du Congo → COD

In [44]:
#️⃣ ♦️ SCRIPT 2G — Application du mapping sur toutes les sources texte - Objectif : ajouter la colonne iso3 à chaque DataFrame
# On applique le dictionnaire sur chaque source
# map() cherche chaque valeur de 'pays' dans le dictionnaire
# Si absent → NaN automatiquement

for nom_df, df in sources_texte.items():
    df["iso3"] = df["pays"].map(mapping_fao_iso3)
    
    # Comptage des NaN = pays sans ISO3 trouvé
    nan_count = df["iso3"].isna().sum()
    total     = len(df)
    
    print(f"\n{'='*50}")
    print(f"{nom_df} — {total} pays — {nan_count} sans ISO3")
    
    # Afficher les pays sans ISO3 pour investigation
    if nan_count > 0:
        manquants = df[df["iso3"].isna()]["pays"].tolist()
        for p in sorted(manquants):
            print(f"  ❌ {p}")

==================================================
pop_2017_df — 236 pays — 2 sans ISO3
  ❌ Chine - RAS de Hong-Kong
  ❌ Chine - RAS de Macao

==================================================
pib_2017_df — 210 pays — 2 sans ISO3
  ❌ Chine - RAS de Hong-Kong
  ❌ Chine - RAS de Macao

==================================================
dispo_2017_df — 172 pays — 2 sans ISO3
  ❌ Chine - RAS de Hong-Kong
  ❌ Chine - RAS de Macao

==================================================
import_poulet_2017_df — 194 pays — 2 sans ISO3
  ❌ Chine - RAS de Hong-Kong
  ❌ Chine - RAS de Macao

==================================================
prod_poulet_2017_df — 195 pays — 2 sans ISO3
  ❌ Chine - RAS de Hong-Kong
  ❌ Chine - RAS de Macao

==================================================
prix_poulet_2017_df — 44 pays — 0 sans ISO3

In [45]:
#️⃣ ♦️ SCRIPT — Diagnostic caractère exact du tiret


# On prend le nom exact tel qu'il est stocké dans pop_2017_df
exemple = pop_2017_df[pop_2017_df["pays"].str.contains("Hong", na=False)]["pays"].values[0]

print(f"Nom exact : '{exemple}'")
print(f"Codes des caractères :")
for i, c in enumerate(exemple):
    print(f"  position {i} : '{c}' → Unicode U+{ord(c):04X}")

Nom exact : 'Chine - RAS de Hong-Kong'
Codes des caractères :
  position 0 : 'C' → Unicode U+0043
  position 1 : 'h' → Unicode U+0068
  position 2 : 'i' → Unicode U+0069
  position 3 : 'n' → Unicode U+006E
  position 4 : 'e' → Unicode U+0065
  position 5 : ' ' → Unicode U+0020
  position 6 : '-' → Unicode U+002D
  position 7 : ' ' → Unicode U+0020
  position 8 : 'R' → Unicode U+0052
  position 9 : 'A' → Unicode U+0041
  position 10 : 'S' → Unicode U+0053
  position 11 : ' ' → Unicode U+0020
  position 12 : 'd' → Unicode U+0064
  position 13 : 'e' → Unicode U+0065
  position 14 : ' ' → Unicode U+0020
  position 15 : 'H' → Unicode U+0048
  position 16 : 'o' → Unicode U+006F
  position 17 : 'n' → Unicode U+006E
  position 18 : 'g' → Unicode U+0067
  position 19 : '-' → Unicode U+002D
  position 20 : 'K' → Unicode U+004B
  position 21 : 'o' → Unicode U+006F
  position 22 : 'n' → Unicode U+006E
  position 23 : 'g' → Unicode U+0067

In [46]:
#️⃣ ♦️ CORRECTION — Tiret cadratin → tiret simple dans le dictionnaire

mapping_fao_iso3["Chine - RAS de Hong-Kong"] = "HKG"
mapping_fao_iso3["Chine - RAS de Macao"]     = "MAC"

# Vérification immédiate — relance le mapping sur toutes les sources
for nom_df, df in sources_texte.items():
    df["iso3"] = df["pays"].map(mapping_fao_iso3)
    nan_count  = df["iso3"].isna().sum()
    print(f"{nom_df} — {nan_count} sans ISO3")

pop_2017_df — 0 sans ISO3
pib_2017_df — 0 sans ISO3
dispo_2017_df — 0 sans ISO3
import_poulet_2017_df — 0 sans ISO3
prod_poulet_2017_df — 0 sans ISO3
prix_poulet_2017_df — 0 sans ISO3

In [47]:
# 🔍 DIAGNOSTIC — Entités chinoises dans chaque source FAO
# À exécuter AVANT tout script de correction

noms_chine = ["Chine", "Chine, continentale", "Chine - RAS de Hong-Kong",
              "Chine - RAS de Macao", "Chine, Taiwan Province de"]

sources = {
    "pop_df"              : pop_df,
    "pib_2017_df"         : pib_2017_df,
    "gouv_2017_df"        : gouv_2017_df,
    "dispo_2017_df"       : dispo_2017_df,
    "import_poulet_2017_df" : import_poulet_2017_df,
    "prod_poulet_2017_df" : prod_poulet_2017_df,
}

for nom_df, df in sources.items():
    if "pays" in df.columns:
        masque = df["pays"].isin(noms_chine)
        found  = df.loc[masque, "pays"].tolist()
        print(f"{nom_df:30s} → {found if found else 'aucune entité chinoise'}")
    else:
        print(f"{nom_df:30s} → colonne 'pays' absente")

pop_df                         → colonne 'pays' absente
pib_2017_df                    → ['Chine - RAS de Hong-Kong', 'Chine - RAS de Macao', 'Chine, continentale']
gouv_2017_df                   → aucune entité chinoise
dispo_2017_df                  → ['Chine - RAS de Hong-Kong', 'Chine - RAS de Macao', 'Chine, Taiwan Province de', 'Chine, continentale']
import_poulet_2017_df          → ['Chine', 'Chine - RAS de Hong-Kong', 'Chine - RAS de Macao', 'Chine, Taiwan Province de', 'Chine, continentale']
prod_poulet_2017_df            → ['Chine', 'Chine - RAS de Hong-Kong', 'Chine - RAS de Macao', 'Chine, continentale', 'Chine, Taiwan Province de']

In [48]:
# 🔍 DIAGNOSTIC 2 — Vérification doublons CHN réels
# À exécuter après la cellule 47

sources = {
    "pib_2017_df"           : pib_2017_df,
    "dispo_2017_df"         : dispo_2017_df,
    "import_poulet_2017_df" : import_poulet_2017_df,
    "prod_poulet_2017_df"   : prod_poulet_2017_df,
}

cibles = ["Chine", "Chine, continentale"]

for nom_df, df in sources.items():
    if "pays" in df.columns:
        found = df[df["pays"].isin(cibles)]["pays"].tolist()
        print(f"{nom_df:30s} → {found}")

pib_2017_df                    → ['Chine, continentale']
dispo_2017_df                  → ['Chine, continentale']
import_poulet_2017_df          → ['Chine', 'Chine, continentale']
prod_poulet_2017_df            → ['Chine', 'Chine, continentale']

<div style="background-color: #d9edf7; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px;">
    
III - Jointure des fichiers

</div>

<div style="background-color: #fff3cd; padding: 12px; border-left: 5px solid #f0ad4e; border-radius: 6px;">

**🔗 Base de départ pour les jointures : `pop_2017_df`**

**Choix justifié :**
- `pop_2017_df` est la source la plus exhaustive : **236 pays**
- Toutes les jointures suivantes sont des **LEFT JOIN sur `iso3`** — aucun pays perdu prématurément
- Les NaN apparaissent uniquement là où une source ne couvre pas un pays
- Le filtre NaN sur variables clés ACP se fait en **section IV**, après consolidation complète — jamais avant

</div>

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 1 : pop_2017_df + pib_2017_df



</div>

In [49]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans pop_2017_df

print(pop_2017_df[
    pop_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

                          pays iso3
785   Chine - RAS de Hong-Kong  HKG
804       Chine - RAS de Macao  MAC
823        Chine, continentale  CHN
842  Chine, Taiwan Province de  TWN

In [50]:
#️⃣ ♦️ EXCLUSION — Entités Chine non retenues dans pop_2017_df

pop_2017_df = pop_2017_df[
    ~pop_2017_df['pays'].str.contains('Chine', na=False) |
    (pop_2017_df['pays'] == 'Chine, continentale')
].copy()

# Vérification
print(f"Lignes après exclusion : {pop_2017_df.shape[0]}")
print(f"\nChines restantes :")
print(pop_2017_df[
    pop_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

Lignes après exclusion : 233

Chines restantes :
                    pays iso3
823  Chine, continentale  CHN

In [51]:
#️⃣ ♦️  Base de départ pour les jointures : pop_2017_df — 236 pays — couverture maximale
# On crée base_df à partir de la population Seules les colonnes utiles sont gardées.copy() évite les effets de bord sur pop_2017_df

base_df = pop_2017_df[["iso3", "pays", "population"]].copy()

# Vérification
print(f"Nombre de pays    : {base_df.shape[0]}")
print(f"Nombre de colonnes: {base_df.shape[1]}")
print(f"Colonnes          : {list(base_df.columns)}")
print(f"Doublons iso3     : {base_df.duplicated(subset='iso3').sum()}")
print(f"NaN iso3          : {base_df['iso3'].isna().sum()}")
print()
print(base_df.head(5))

Nombre de pays    : 233
Nombre de colonnes: 3
Colonnes          : ['iso3', 'pays', 'population']
Doublons iso3     : 0
NaN iso3          : 0

   iso3            pays  population
17  AFG     Afghanistan  36296113.0
36  ZAF  Afrique du Sud  57009756.0
55  ALB         Albanie   2884169.0
74  DZA         Algérie  41389189.0
93  DEU       Allemagne  82658409.0

In [52]:
#️⃣ ♦️ PIB - On ajoute pib_total_millions_usd et pib_par_habitant_usd

# Jointure PIB uniquement
pib_join  = pib_2017_df[["iso3", "pib_total_millions_usd", "pib_par_habitant_usd"]].copy()
base_df   = base_df.merge(pib_join, on="iso3", how="left")

# Contrôle strict
assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert list(base_df.columns) == [
    "iso3", "pays", "population",
    "pib_total_millions_usd", "pib_par_habitant_usd"
], "ERREUR : colonnes incorrectes"

print(f"✅ Pays    : {base_df.shape[0]}")
print(f"✅ Colonnes: {list(base_df.columns)}")

✅ Pays    : 233
✅ Colonnes: ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd']

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 2 — Gouvernance.



</div>

In [53]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans gouv_2017_df

print(gouv_2017_df[
    gouv_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

Empty DataFrame
Columns: [pays, iso3]
Index: []

In [54]:
#️⃣ ♦️ JOINTURE 2 — Stabilité politique (World Bank Governance)

gouv_join = gouv_2017_df[["iso3", "stabilite_politique"]].copy()
base_df   = base_df.merge(gouv_join, on="iso3", how="left")

print(f"Source Gouvernance : {gouv_join.shape[0]} pays x {gouv_join.shape[1]} colonnes")
print(f"Doublons iso3      : {gouv_join.duplicated(subset='iso3').sum()}")
print(f"NaN iso3           : {gouv_join['iso3'].isna().sum()}")

Source Gouvernance : 205 pays x 2 colonnes
Doublons iso3      : 0
NaN iso3           : 0

In [55]:
#️⃣ ♦️ Vérification
assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert "stabilite_politique" in base_df.columns, "ERREUR : colonne manquante"
assert "stabilite_politique_x" not in base_df.columns, "ERREUR : doublon colonne"

print(f" Pays     : {base_df.shape[0]}")
print(f" Colonnes : {list(base_df.columns)}")
print(f" NaN gouv : {base_df['stabilite_politique'].isna().sum()}")

 Pays     : 233
 Colonnes : ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd', 'stabilite_politique']
 NaN gouv : 31

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 3 — Disponibilité alimentaire



</div>

In [56]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans dispo_2017_df

print(dispo_2017_df[
    dispo_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

                         pays iso3
31   Chine - RAS de Hong-Kong  HKG
32       Chine - RAS de Macao  MAC
33  Chine, Taiwan Province de  TWN
34        Chine, continentale  CHN

In [57]:
#️⃣ ♦️ EXCLUSION — Entités Chine non retenues dans dispo_2017_df

dispo_2017_df = dispo_2017_df[
    ~dispo_2017_df['pays'].str.contains('Chine', na=False) |
    (dispo_2017_df['pays'] == 'Chine, continentale')
].copy()

# Vérification
print(f"Lignes après exclusion : {dispo_2017_df.shape[0]}")
print(f"\nChines restantes :")
print(dispo_2017_df[
    dispo_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

Lignes après exclusion : 169

Chines restantes :
                   pays iso3
34  Chine, continentale  CHN

In [58]:
#️⃣ ♦️ Disponibilité alimentaire — Préparation source

dispo_join = dispo_2017_df[["iso3",
                             "dispo_interieure_tonnes",
                             "importations_tonnes",
                             "exportations_tonnes",
                             "conso_volaille_kg_hab_an"]].copy()

print(f"Source Dispo   : {dispo_join.shape[0]} pays x {dispo_join.shape[1]} colonnes")
print(f"Doublons iso3  : {dispo_join.duplicated(subset='iso3').sum()}")
print(f"NaN iso3       : {dispo_join['iso3'].isna().sum()}")

Source Dispo   : 169 pays x 5 colonnes
Doublons iso3  : 0
NaN iso3       : 0

In [59]:
#️⃣ ♦️— Disponibilité alimentaire — merge LEFT JOIN


base_df = base_df.merge(dispo_join, on="iso3", how="left")

assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert "dispo_interieure_tonnes_x" not in base_df.columns, "ERREUR : doublon colonne"

print(f" Pays     : {base_df.shape[0]}")
print(f" Colonnes : {list(base_df.columns)}")
print(f"NaN conso_volaille : {base_df['conso_volaille_kg_hab_an'].isna().sum()}")
print(f"NaN dispo_interieure : {base_df['dispo_interieure_tonnes'].isna().sum()}")

 Pays     : 233
 Colonnes : ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd', 'stabilite_politique', 'dispo_interieure_tonnes', 'importations_tonnes', 'exportations_tonnes', 'conso_volaille_kg_hab_an']
NaN conso_volaille : 64
NaN dispo_interieure : 66

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 4 — Importations poulet



</div>

In [60]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans import_poulet_2017_df

print(import_poulet_2017_df[
    import_poulet_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

                         pays iso3
35                      Chine  CHN
36   Chine - RAS de Hong-Kong  HKG
37       Chine - RAS de Macao  MAC
38  Chine, Taiwan Province de  TWN
39        Chine, continentale  CHN

In [61]:
#️⃣ ♦️ EXCLUSION — Entités Chine non retenues dans import_poulet_2017_df

ISO3_A_EXCLURE = ['HKG', 'MAC', 'TWN']

PAYS_A_EXCLURE = ['Chine']  # agrégat — doublon CHN avec Chine, continentale

import_poulet_2017_df = import_poulet_2017_df[
    ~import_poulet_2017_df['iso3'].isin(ISO3_A_EXCLURE) &
    ~import_poulet_2017_df['pays'].isin(PAYS_A_EXCLURE)
].copy()

# Vérification
print(f"Lignes après exclusion : {import_poulet_2017_df.shape[0]}")
print(f"Doublons iso3          : {import_poulet_2017_df['iso3'].duplicated().sum()}")
print(f"\nChines restantes :")
print(import_poulet_2017_df[
    import_poulet_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

Lignes après exclusion : 190
Doublons iso3          : 0

Chines restantes :
                   pays iso3
39  Chine, continentale  CHN

In [62]:
#️⃣ ♦️ Importations poulet — Préparation source


import_join = import_poulet_2017_df[["iso3",
                                      "import_qty_tonnes",
                                      "import_value_kusd",
                                      "import_declared"]].copy()

print(f"Source Imports : {import_join.shape[0]} pays x {import_join.shape[1]} colonnes")
print(f"Doublons iso3  : {import_join.duplicated(subset='iso3').sum()}")
print(f"NaN iso3       : {import_join['iso3'].isna().sum()}")

Source Imports : 190 pays x 4 colonnes
Doublons iso3  : 0
NaN iso3       : 0

In [63]:
#️⃣ ♦️ DIAGNOSTIC — Taille de base_df après merge jointure 4

print(f"Nombre de lignes base_df : {base_df.shape[0]}")
print(f"Doublons iso3 dans base_df : {base_df['iso3'].duplicated().sum()}")

Nombre de lignes base_df : 233
Doublons iso3 dans base_df : 0

In [64]:
#️⃣ ♦️Importations poulet — merge LEFT JOIN


base_df = base_df.merge(import_join, on="iso3", how="left")

assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert "import_qty_tonnes_x" not in base_df.columns, "ERREUR : doublon colonne"

print(f" Pays    : {base_df.shape[0]}")
print(f" Colonnes: {list(base_df.columns)}")
print(f"NaN import_qty : {base_df['import_qty_tonnes'].isna().sum()}")

 Pays    : 233
 Colonnes: ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd', 'stabilite_politique', 'dispo_interieure_tonnes', 'importations_tonnes', 'exportations_tonnes', 'conso_volaille_kg_hab_an', 'import_qty_tonnes', 'import_value_kusd', 'import_declared']
NaN import_qty : 43

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 5 — Production poulet



</div>

In [65]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans prod_poulet_2017_df

print(prod_poulet_2017_df[
    prod_poulet_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

                         pays iso3
35                      Chine  CHN
36   Chine - RAS de Hong-Kong  HKG
37       Chine - RAS de Macao  MAC
38        Chine, continentale  CHN
39  Chine, Taiwan Province de  TWN

In [66]:
#️⃣ ♦️ EXCLUSION — Entités Chine non retenues dans prod_poulet_2017_df

PAYS_A_GARDER_CHINE = 'Chine, continentale'

prod_poulet_2017_df = prod_poulet_2017_df[
    ~prod_poulet_2017_df['pays'].str.contains('Chine', na=False) |
    (prod_poulet_2017_df['pays'] == PAYS_A_GARDER_CHINE)
].copy()

# Vérification
print(f"Lignes après exclusion : {prod_poulet_2017_df.shape[0]}")
print(f"Doublons iso3          : {prod_poulet_2017_df['iso3'].duplicated().sum()}")
print(f"\nChines restantes :")
print(prod_poulet_2017_df[
    prod_poulet_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

Lignes après exclusion : 191
Doublons iso3          : 0

Chines restantes :
                   pays iso3
38  Chine, continentale  CHN

In [67]:
#️⃣ ♦️ Production poulet — Préparation source

prod_join = prod_poulet_2017_df[["iso3",
                                  "production_tonnes"]].copy()

print(f"Source Production : {prod_join.shape[0]} pays x {prod_join.shape[1]} colonnes")
print(f"Doublons iso3     : {prod_join.duplicated(subset='iso3').sum()}")
print(f"NaN iso3          : {prod_join['iso3'].isna().sum()}")

Source Production : 191 pays x 2 colonnes
Doublons iso3     : 0
NaN iso3          : 0

In [68]:
#️⃣ ♦️ Production poulet — merge LEFT JOIN


base_df = base_df.merge(prod_join, on="iso3", how="left")

assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert "production_tonnes_x" not in base_df.columns, "ERREUR : doublon colonne"

print(f" Pays    : {base_df.shape[0]}")
print(f" Colonnes: {list(base_df.columns)}")
print(f"NaN production : {base_df['production_tonnes'].isna().sum()}")

 Pays    : 233
 Colonnes: ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd', 'stabilite_politique', 'dispo_interieure_tonnes', 'importations_tonnes', 'exportations_tonnes', 'conso_volaille_kg_hab_an', 'import_qty_tonnes', 'import_value_kusd', 'import_declared', 'production_tonnes']
NaN production : 42

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 6 — Prix producteur



</div>

In [69]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans prix_poulet_2017_df

print(prix_poulet_2017_df[
    prix_poulet_2017_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

                   pays iso3
10  Chine, continentale  CHN

In [70]:
#️⃣♦️ Prix producteur — Préparation source


prix_join = prix_poulet_2017_df[["iso3", "prix_prod_usd_tonne"]].copy()

print(f"Source Prix    : {prix_join.shape[0]} pays x {prix_join.shape[1]} colonnes")
print(f"Doublons iso3  : {prix_join.duplicated(subset='iso3').sum()}")
print(f"NaN iso3       : {prix_join['iso3'].isna().sum()}")

Source Prix    : 44 pays x 2 colonnes
Doublons iso3  : 0
NaN iso3       : 0

In [71]:
#️⃣♦️ Prix producteur — merge LEFT JOIN

base_df = base_df.merge(prix_join, on="iso3", how="left")

assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert "prix_prod_usd_tonne_x" not in base_df.columns, "ERREUR : doublon colonne"

print(f" Pays    : {base_df.shape[0]}")
print(f" Colonnes: {list(base_df.columns)}")
print(f"NaN prix_prod : {base_df['prix_prod_usd_tonne'].isna().sum()}")

 Pays    : 233
 Colonnes: ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd', 'stabilite_politique', 'dispo_interieure_tonnes', 'importations_tonnes', 'exportations_tonnes', 'conso_volaille_kg_hab_an', 'import_qty_tonnes', 'import_value_kusd', 'import_declared', 'production_tonnes', 'prix_prod_usd_tonne']
NaN prix_prod : 189

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    🔗 – JOINTURE 7 — Distance CEPII



</div>

In [72]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans dist_2017_df

print(dist_2017_df[
    dist_2017_df['iso3'].isin(['CHN', 'HKG', 'MAC', 'TWN'])
][['iso3']])

      iso3
15045  CHN
15094  HKG
15128  MAC
15212  TWN

In [73]:
#️⃣ ♦️ EXCLUSION — Entités Chine non retenues dans dist_2017_df

dist_2017_df = dist_2017_df[
    ~dist_2017_df['iso3'].isin(['HKG', 'MAC', 'TWN'])
].copy()

# Vérification
print(f"Lignes après exclusion : {dist_2017_df.shape[0]}")
print(f"\nChines restantes :")
print(dist_2017_df[
    dist_2017_df['iso3'].isin(['CHN', 'HKG', 'MAC', 'TWN'])
][['iso3']])

Lignes après exclusion : 220

Chines restantes :
      iso3
15045  CHN

In [74]:
#️⃣ ♦️ Distance CEPII — Préparation source

dist_join = dist_2017_df[["iso3", "distance_km",
                           "distance_simple_km",
                           "contig", "comlang_off"]].copy()

print(f"Source Distance : {dist_join.shape[0]} pays x {dist_join.shape[1]} colonnes")
print(f"Doublons iso3   : {dist_join.duplicated(subset='iso3').sum()}")
print(f"NaN iso3        : {dist_join['iso3'].isna().sum()}")

Source Distance : 220 pays x 5 colonnes
Doublons iso3   : 0
NaN iso3        : 0

In [75]:
#️⃣ ♦️ JOINTURE 7 — Distance CEPII — merge LEFT JOIN — DERNIÈRE JOINTURE


base_df = base_df.merge(dist_join, on="iso3", how="left")

assert base_df.shape[0] == 233, "ERREUR : nombre de pays incorrect"
assert "distance_km_x" not in base_df.columns, "ERREUR : doublon colonne"

print(f" Pays    : {base_df.shape[0]}")
print(f" Colonnes: {list(base_df.columns)}")
print(f"\n=== NaN par colonne ===")
print(base_df.isnull().sum())

 Pays    : 233
 Colonnes: ['iso3', 'pays', 'population', 'pib_total_millions_usd', 'pib_par_habitant_usd', 'stabilite_politique', 'dispo_interieure_tonnes', 'importations_tonnes', 'exportations_tonnes', 'conso_volaille_kg_hab_an', 'import_qty_tonnes', 'import_value_kusd', 'import_declared', 'production_tonnes', 'prix_prod_usd_tonne', 'distance_km', 'distance_simple_km', 'contig', 'comlang_off']

=== NaN par colonne ===
iso3                          0
pays                          0
population                    0
pib_total_millions_usd       25
pib_par_habitant_usd         25
stabilite_politique          31
dispo_interieure_tonnes      66
importations_tonnes          66
exportations_tonnes         101
conso_volaille_kg_hab_an     64
import_qty_tonnes            43
import_value_kusd            43
import_declared              43
production_tonnes            42
prix_prod_usd_tonne         189
distance_km                  23
distance_simple_km           22
contig                       22
comlang_off                  22
dtype: int64

In [76]:
#️⃣ ♦️ VÉRIFICATION — Entités Chine dans base_df final

print(base_df[
    base_df['pays'].str.contains('Chine', na=False)
][['pays', 'iso3']])

                   pays iso3
41  Chine, continentale  CHN

<div style="background-color: #d9edf7; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px;">
    
IV - Nettoyage du dataset : base_df
</div>

**Objectif de cette section :**

1. Supprimer les pays avec trop de NaN sur les variables clés de l'ACP — un pays sans PIB, sans stabilité politique ET sans consommation n'est pas exploitable
2. Vérifier le seuil des 100 pays — exigence du projet

In [77]:
#️⃣ ♦️ Filtre NaN sur variables clés ACP - Seuil : max 2 NaN tolérés sur les 7 variables clés

#️⃣ Variables clés retenues pour l'ACP
variables_cles = [
    "population",
    "pib_par_habitant_usd",
    "stabilite_politique",
    "conso_volaille_kg_hab_an",
    "import_qty_tonnes",
    "production_tonnes",
    "distance_km"
]

#️⃣ Comptage des NaN par pays sur ces 7 variables uniquement
base_df["nb_nan_cles"] = base_df[variables_cles].isnull().sum(axis=1)

#️⃣ Distribution des NaN pour décider
print("=== Distribution des NaN sur variables clés ===\n")
print(base_df["nb_nan_cles"].value_counts().sort_index())

print(f"\nPays avec 0 NaN  : {(base_df['nb_nan_cles'] == 0).sum()}")
print(f"Pays avec 1 NaN  : {(base_df['nb_nan_cles'] == 1).sum()}")
print(f"Pays avec 2 NaN  : {(base_df['nb_nan_cles'] == 2).sum()}")
print(f"Pays avec 3+ NaN : {(base_df['nb_nan_cles'] >= 3).sum()}")
print(f"\nTotal gardés (≤2 NaN) : {(base_df['nb_nan_cles'] <= 2).sum()}")
print(f"Total exclus (>2 NaN) : {(base_df['nb_nan_cles'] > 2).sum()}")

=== Distribution des NaN sur variables clés ===

nb_nan_cles
0    155
1     32
2      7
3      7
4      6
5     19
6      7
Name: count, dtype: int64

Pays avec 0 NaN  : 155
Pays avec 1 NaN  : 32
Pays avec 2 NaN  : 7
Pays avec 3+ NaN : 39

Total gardés (≤2 NaN) : 194
Total exclus (>2 NaN) : 39

In [78]:
#️⃣ ♦️ Filtre strict : 0 NaN sur variables clés ACP - Exigence auto-évaluation : aucun vide dans la matrice ACP

print(f"Pays avant filtrage : {base_df.shape[0]}")

#️⃣ On garde uniquement les pays complets sur les 7 variables clés
base_df = base_df[base_df["nb_nan_cles"] == 0].copy()

#️⃣ Suppression colonne de comptage
base_df = base_df.drop(columns=["nb_nan_cles"])

print(f"Pays après filtrage : {base_df.shape[0]}")
print(f"Colonnes            : {base_df.shape[1]}")
print(f"\n=== NaN par colonne ===")
print(base_df.isnull().sum())

Pays avant filtrage : 233
Pays après filtrage : 155
Colonnes            : 19

=== NaN par colonne ===
iso3                          0
pays                          0
population                    0
pib_total_millions_usd        0
pib_par_habitant_usd          0
stabilite_politique           0
dispo_interieure_tonnes       2
importations_tonnes           2
exportations_tonnes          32
conso_volaille_kg_hab_an      0
import_qty_tonnes             0
import_value_kusd             0
import_declared               0
production_tonnes             0
prix_prod_usd_tonne         116
distance_km                   0
distance_simple_km            0
contig                        0
comlang_off                   0
dtype: int64

In [79]:
print(base_df['dispo_interieure_tonnes'].isna().sum())

2

In [80]:
#️⃣ ♦️ Nettoyage final + création des variables dérivées-  Suppression des 2 pays avec NaN sur dispo_interieure_tonnes ---

# On identifie d'abord les pays concernés avant de les supprimer
# Règle : toujours savoir CE QU'ON SUPPRIME avant de supprimer
pays_nan_dispo = base_df[base_df['dispo_interieure_tonnes'].isna()]['pays'].tolist()
print("Pays supprimés (NaN dispo_interieure_tonnes) :", pays_nan_dispo)

# Suppression en place — on écrase base_df proprement
base_df = base_df.dropna(subset=['dispo_interieure_tonnes']).copy()

# Vérification immédiate
print(f"\nPays après suppression : {base_df.shape[0]}")  # Attendu : 153
print(f"NaN restants sur dispo_interieure_tonnes : {base_df['dispo_interieure_tonnes'].isna().sum()}")  # Attendu : 0

Pays supprimés (NaN dispo_interieure_tonnes) : ['Ouzbékistan', 'République démocratique populaire lao']

Pays après suppression : 153
NaN restants sur dispo_interieure_tonnes : 0

<div style="background-color: #d9edf7; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px;">
    
V - Feature Engineering : base_df
</div>

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    📊 – Variable 1/3 : marche_volaille_t   -   Taille réelle du marché volaille en tonnes



</div>

In [81]:
#️⃣♦️ Formule : consommation par habitant (kg) × population / 1000 - La division par 1000 convertit les kg en tonnes

base_df['marche_volaille_t'] = (
    base_df['conso_volaille_kg_hab_an'] * base_df['population'] / 1000
)

# Vérification 
print("NaN :", base_df['marche_volaille_t'].isna().sum())  # Attendu : 0
print(base_df['marche_volaille_t'].describe().round(0))

NaN : 0
count         153.0
mean       701618.0
std       2245064.0
min          1961.0
25%         29729.0
50%        100924.0
75%        348110.0
max      18100719.0
Name: marche_volaille_t, dtype: float64

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    📊 – Variable  2/3 : taux_dependance_import   -   Part des importations poulet dans la disponibilité intérieure volaille



</div>

In [82]:
#️⃣♦️ Formule : imports poulet TCL / disponibilité intérieure volaille
     # Résultat attendu : majoritairement entre 0 et 1
     # Valeurs > 1 possibles — proxy imparfait entre deux sources différentes

base_df['taux_dependance_import'] = (
    base_df['import_qty_tonnes'] / base_df['dispo_interieure_tonnes']
)

#️⃣♦️ Vérification
print("NaN :", base_df['taux_dependance_import'].isna().sum())  # Attendu : 0
print(base_df['taux_dependance_import'].describe().round(3))

#️⃣♦️ Combien de pays ont un taux > 1 ? (signal à surveiller)
print("\nPays avec taux > 1 :",
      (base_df['taux_dependance_import'] > 1).sum())

NaN : 0
count    153.000
mean       0.336
std        0.381
min        0.000
25%        0.027
50%        0.187
75%        0.612
max        1.998
Name: taux_dependance_import, dtype: float64

Pays avec taux > 1 : 11

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    📊 – Variable  3/3 : taux_couverture_locale   -   Mesure si le pays couvre son marché avec sa production locale



</div>

In [83]:
#️⃣♦️  Formule : production locale / disponibilité intérieure
# < 1 = le pays ne produit pas assez, il doit importer → cible potentielle
# > 1 = le pays est autosuffisant ou exportateur → cible moins prioritaire
base_df['taux_couverture_locale'] = (
    base_df['production_tonnes'] / base_df['dispo_interieure_tonnes']
)

#️⃣♦️  Vérification ---
print("NaN :", base_df['taux_couverture_locale'].isna().sum())  # Attendu : 0
print(base_df['taux_couverture_locale'].describe().round(3))

#️⃣♦️  Répartition métier
print("\nPays < 1 (besoin d'import) :",
      (base_df['taux_couverture_locale'] < 1).sum())
print("Pays > 1 (autosuffisants)  :",
      (base_df['taux_couverture_locale'] > 1).sum())

NaN : 0
count    153.000
mean       0.829
std        0.682
min        0.003
25%        0.357
50%        0.814
75%        1.032
max        4.813
Name: taux_couverture_locale, dtype: float64

Pays < 1 (besoin d'import) : 111
Pays > 1 (autosuffisants)  : 42

<div style="background-color: #e8f5e9; padding: 12px; border-left: 5px solid #2e7d32; border-radius: 6px;">
    
    📊 – Dataframe finale : base_df - Les 11 variables  



</div>

In [84]:
#️⃣♦️ Vérification shape finale et colonnes ACP
print(f"Shape base_df : {base_df.shape}")  # Attendu : 154 x 22

variables_acp = [
    'population', 'pib_par_habitant_usd', 'stabilite_politique',
    'conso_volaille_kg_hab_an', 'import_qty_tonnes', 'production_tonnes',
    'distance_km', 'exportations_tonnes', 'marche_volaille_t',
    'taux_dependance_import', 'taux_couverture_locale'
]

print(f"\nNaN sur les 11 variables ACP :")
print(base_df[variables_acp].isna().sum())

Shape base_df : (153, 22)

NaN sur les 11 variables ACP :
population                   0
pib_par_habitant_usd         0
stabilite_politique          0
conso_volaille_kg_hab_an     0
import_qty_tonnes            0
production_tonnes            0
distance_km                  0
exportations_tonnes         30
marche_volaille_t            0
taux_dependance_import       0
taux_couverture_locale       0
dtype: int64

In [85]:
#️⃣ ♦️ÉTAPE 4 — Nettoyage final- Imputation des NaN sur exportations_tonnes
# Convention FAO : NaN = absence d'export déclaré = 0

#️⃣ ♦️ Vérification avant imputation
print("NaN avant imputation :", 
      base_df['exportations_tonnes'].isna().sum())  # Attendu : 30

#️⃣ ♦️ Imputation à 0
base_df['exportations_tonnes'] = (
    base_df['exportations_tonnes'].fillna(0)
)

#️⃣ ♦️ Vérification après imputation
print("NaN après imputation :", 
      base_df['exportations_tonnes'].isna().sum())  # Attendu : 0

#️⃣ ♦️ Vérification que les autres variables ACP sont toujours à 0 NaN
print("\nNaN sur les 11 variables ACP :")
print(base_df[variables_acp].isna().sum())

NaN avant imputation : 30
NaN après imputation : 0

NaN sur les 11 variables ACP :
population                  0
pib_par_habitant_usd        0
stabilite_politique         0
conso_volaille_kg_hab_an    0
import_qty_tonnes           0
production_tonnes           0
distance_km                 0
exportations_tonnes         0
marche_volaille_t           0
taux_dependance_import      0
taux_couverture_locale      0
dtype: int64

<div style="background-color: #d9edf7; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px;">
    
VI - Documentation des variables : Justification métier et rôle pipeline de chaque variable
</div>

In [86]:
#️⃣ ♦️ Dictionnaire de justification — 1 entrée par variableETAPE 4 — Documentation des variables
# Justification metier et role pipeline de chaque variable

# Dictionnaire de justification — 1 entree par variable
variables_doc = {
    'iso3': {
        'type': 'Identifiant',
        'role_pipeline': 'Cle de jointure',
        'dans_acp': 'Non',
        'justification_metier': "Code pays ISO3 — cle technique de jointure entre toutes les sources. Non interpretable statistiquement."
    },
    'pays': {
        'type': 'Identifiant',
        'role_pipeline': 'Label',
        'dans_acp': 'Non',
        'justification_metier': "Nom du pays en francais — utilise pour l'affichage et l'interpretation des resultats clustering."
    },
    'population': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Social. Mesure la taille demographique du marche. Un pays de 100M habitants n'a pas le meme potentiel qu'un pays de 1M."
    },
    'pib_par_habitant_usd': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Economique. Mesure le pouvoir d'achat. Un pays pauvre ne peut pas acheter du poulet importe meme s'il en manque."
    },
    'pib_total_millions_usd': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "PESTEL — Economique. Conserve pour analyses descriptives. Exclu ACP : trop correle a population x pib_par_habitant — apport redondant."
    },
    'stabilite_politique': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Politique. Score World Bank [-2.5 ; +2.5]. Mesure le risque pays. Un pays instable represente un risque contractuel et logistique eleve."
    },
    'dispo_interieure_tonnes': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Variable technique — denominateur des ratios taux_dependance_import et taux_couverture_locale. Exclu ACP : redondant avec ses composantes (production + imports)."
    },
    'importations_tonnes': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Doublon fonctionnel de import_qty_tonnes (source FAO disponibilite vs FAO TCL). Conserve pour tracabilite. Exclu ACP : perimetre moins precis que import_qty_tonnes."
    },
    'exportations_tonnes': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Economique. Volume exporte de volaille. Identifie les pays exportateurs nets — cibles moins prioritaires pour l'export francais. 30 NaN imputes a 0 (convention FAO : absence de ligne = absence d'export declare)."
    },
    'conso_volaille_kg_hab_an': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Social. Mesure l'appetence culturelle pour la volaille par habitant. Independent du volume total — capture la demande unitaire."
    },
    'import_qty_tonnes': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Economique. Volume importe de poulet frais/refrigere (source TCL — plus precise). Signal d'ouverture du marche et d'habitudes d'achat etablies."
    },
    'import_value_kusd': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Conserve pour calcul prix_implicite_import en analyse descriptive. Exclu ACP : tres correle a import_qty_tonnes — apport redondant."
    },
    'import_declared': {
        'type': 'Flag qualite',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Flag technique (0/1) — indique si la donnee import est reelle ou imputee. Utile pour ponderer la confiance dans import_qty_tonnes."
    },
    'production_tonnes': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Economique. Volume produit localement. Un pays avec forte production locale = concurrent domestique fort = marche moins accessible."
    },
    'prix_prod_usd_tonne': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "PESTEL — Economique. Prix producteur local. Exclu ACP : 117 NaN sur 153 pays (76%) — inclusion impossible sans perdre les 2/3 de l'echantillon."
    },
    'distance_km': {
        'type': 'Variable source',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "PESTEL — Environnemental/Logistique. Distance ponderee population France -> pays (CEPII distw). Proxy direct du cout logistique export."
    },
    'distance_simple_km': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Fallback technique pour les 5 pays avec NaN sur distance_km. Conserve pour tracabilite."
    },
    'contig': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Frontiere commune avec la France (0/1). Exclu ACP : variable binaire peu discriminante — quasi constante a 0 sur 154 pays."
    },
    'comlang_off': {
        'type': 'Variable source',
        'role_pipeline': 'Hors ACP',
        'dans_acp': 'Non',
        'justification_metier': "Langue officielle commune avec la France (0/1). Exclu ACP : variable binaire, peu de pays francophones dans l'echantillon — faible pouvoir discriminant."
    },
    'marche_volaille_t': {
        'type': 'Feature engineering',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "FE — Taille reelle du marche en tonnes (conso_kg_hab x population / 1000). Combine la demande unitaire et la taille demographique — information non capturee par chacune separement."
    },
    'taux_dependance_import': {
        'type': 'Feature engineering',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "FE — Part des imports dans la disponibilite interieure (import_qty / dispo_interieure). Mesure la dependance structurelle aux importations. Ratio normalise, non correle aux volumes bruts."
    },
    'taux_couverture_locale': {
        'type': 'Feature engineering',
        'role_pipeline': 'ACP',
        'dans_acp': 'Oui',
        'justification_metier': "FE — Autosuffisance du pays (production / dispo_interieure). < 1 = besoin d'import = cible potentielle. > 1 = autosuffisant ou exportateur = cible moins prioritaire."
    }
}

# Construction du DataFrame de documentation
doc_df = pd.DataFrame(variables_doc).T.reset_index()
doc_df.columns = ['variable', 'type', 'role_pipeline', 'dans_acp', 'justification_metier']

# Affichage structure
print(f"Variables documentees : {len(doc_df)}")
print(f"Variables dans ACP   : {(doc_df['dans_acp'] == 'Oui').sum()}")
print(f"Variables hors ACP   : {(doc_df['dans_acp'] == 'Non').sum()}")
print()

# Affichage par groupe
for role in ['ACP', 'Hors ACP', 'Cle de jointure', 'Label']:
    subset = doc_df[doc_df['role_pipeline'] == role]
    if len(subset) > 0:
        print(f"\n{'='*60}")
        print(f"  {role} ({len(subset)} variables)")
        print(f"{'='*60}")
        for _, row in subset.iterrows():
            print(f"\n> {row['variable']} [{row['type']}]")
            print(f"  {row['justification_metier']}")

Variables documentees : 22
Variables dans ACP   : 11
Variables hors ACP   : 11


============================================================
  ACP (11 variables)
============================================================

> population [Variable source]
  PESTEL — Social. Mesure la taille demographique du marche. Un pays de 100M habitants n'a pas le meme potentiel qu'un pays de 1M.

> pib_par_habitant_usd [Variable source]
  PESTEL — Economique. Mesure le pouvoir d'achat. Un pays pauvre ne peut pas acheter du poulet importe meme s'il en manque.

> stabilite_politique [Variable source]
  PESTEL — Politique. Score World Bank [-2.5 ; +2.5]. Mesure le risque pays. Un pays instable represente un risque contractuel et logistique eleve.

> exportations_tonnes [Variable source]
  PESTEL — Economique. Volume exporte de volaille. Identifie les pays exportateurs nets — cibles moins prioritaires pour l'export francais. 30 NaN imputes a 0 (convention FAO : absence de ligne = absence d'export declare).

> conso_volaille_kg_hab_an [Variable source]
  PESTEL — Social. Mesure l'appetence culturelle pour la volaille par habitant. Independent du volume total — capture la demande unitaire.

> import_qty_tonnes [Variable source]
  PESTEL — Economique. Volume importe de poulet frais/refrigere (source TCL — plus precise). Signal d'ouverture du marche et d'habitudes d'achat etablies.

> production_tonnes [Variable source]
  PESTEL — Economique. Volume produit localement. Un pays avec forte production locale = concurrent domestique fort = marche moins accessible.

> distance_km [Variable source]
  PESTEL — Environnemental/Logistique. Distance ponderee population France -> pays (CEPII distw). Proxy direct du cout logistique export.

> marche_volaille_t [Feature engineering]
  FE — Taille reelle du marche en tonnes (conso_kg_hab x population / 1000). Combine la demande unitaire et la taille demographique — information non capturee par chacune separement.

> taux_dependance_import [Feature engineering]
  FE — Part des imports dans la disponibilite interieure (import_qty / dispo_interieure). Mesure la dependance structurelle aux importations. Ratio normalise, non correle aux volumes bruts.

> taux_couverture_locale [Feature engineering]
  FE — Autosuffisance du pays (production / dispo_interieure). < 1 = besoin d'import = cible potentielle. > 1 = autosuffisant ou exportateur = cible moins prioritaire.

============================================================
  Hors ACP (9 variables)
============================================================

> pib_total_millions_usd [Variable source]
  PESTEL — Economique. Conserve pour analyses descriptives. Exclu ACP : trop correle a population x pib_par_habitant — apport redondant.

> dispo_interieure_tonnes [Variable source]
  Variable technique — denominateur des ratios taux_dependance_import et taux_couverture_locale. Exclu ACP : redondant avec ses composantes (production + imports).

> importations_tonnes [Variable source]
  Doublon fonctionnel de import_qty_tonnes (source FAO disponibilite vs FAO TCL). Conserve pour tracabilite. Exclu ACP : perimetre moins precis que import_qty_tonnes.

> import_value_kusd [Variable source]
  Conserve pour calcul prix_implicite_import en analyse descriptive. Exclu ACP : tres correle a import_qty_tonnes — apport redondant.

> import_declared [Flag qualite]
  Flag technique (0/1) — indique si la donnee import est reelle ou imputee. Utile pour ponderer la confiance dans import_qty_tonnes.

> prix_prod_usd_tonne [Variable source]
  PESTEL — Economique. Prix producteur local. Exclu ACP : 117 NaN sur 153 pays (76%) — inclusion impossible sans perdre les 2/3 de l'echantillon.

> distance_simple_km [Variable source]
  Fallback technique pour les 5 pays avec NaN sur distance_km. Conserve pour tracabilite.

> contig [Variable source]
  Frontiere commune avec la France (0/1). Exclu ACP : variable binaire peu discriminante — quasi constante a 0 sur 154 pays.

> comlang_off [Variable source]
  Langue officielle commune avec la France (0/1). Exclu ACP : variable binaire, peu de pays francophones dans l'echantillon — faible pouvoir discriminant.

============================================================
  Cle de jointure (1 variables)
============================================================

> iso3 [Identifiant]
  Code pays ISO3 — cle technique de jointure entre toutes les sources. Non interpretable statistiquement.

============================================================
  Label (1 variables)
============================================================

> pays [Identifiant]
  Nom du pays en francais — utilise pour l'affichage et l'interpretation des resultats clustering.

In [87]:
#️⃣ ♦️ Export base_df — fichier de travail pour le Notebook 2

# Chemin de sauvegarde — à adapter à ton environnement
base_df.to_csv("base_df_final.csv", index=False, encoding="utf-8-sig")

# Vérification
print(f"Export réussi : {base_df.shape[0]} pays x {base_df.shape[1]} colonnes")
print(f"Fichier : base_df_final.csv")

Export réussi : 153 pays x 22 colonnes
Fichier : base_df_final.csv